In [1]:
! nvidia-smi

Thu Oct 15 04:09:07 2026
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 595.99.02              Driver Version: 595.99.02      CUDA Version: 13.2     |
+-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce RTX 4060 ...    Off |   00000000:01:00.0 Off |                  N/A |
| N/A   57C    P3             13W /   55W |      15MiB /   8188MiB |     14%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+

+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI              PID   Type   Process name                        GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|    0   N/A  N/A            5294      G   /usr/lib/xorg/Xorg                        4MiB |
+-----------------------------------------------------------------------------------------+

In [2]:
import io, os, sys, zipfile, urllib.request
from pathlib import Path

if "google.colab" in sys.modules:
    os.chdir("/content")
    sys.path.insert(0, "/content")

    need_src = True
    need_data = not Path("data/ecommerce/gt_images.json").exists()
    need_req = True
    if need_src or need_data or need_req:
        url = "https://codeload.github.com/ranjanrakesh47g/ObjectDetection/zip/refs/heads/main"
        with zipfile.ZipFile(io.BytesIO(urllib.request.urlopen(url).read())) as zipped:
            prefix = next(name for name in zipped.namelist() if name.endswith("data/ecommerce/gt_images.json")).split("data/")[0]
            names = []
            if need_req:
                names.append(prefix + "requirements.txt")
            if need_data:
                names += [name for name in zipped.namelist() if name.startswith(prefix + "data/") and not name.endswith("/")]
            if need_src:
                names += [name for name in zipped.namelist() if name.startswith(prefix + "src/") and not name.endswith("/")]
            for name in names:
                dest = Path(name[len(prefix):])
                dest.parent.mkdir(parents=True, exist_ok=True)
                dest.write_bytes(zipped.read(name))

    get_ipython().run_line_magic("pip", "install -q -r requirements.txt")
    if not Path("/tmp/colab_restarted").exists():
        Path("/tmp/colab_restarted").write_text("1")
        print("Restarting the runtime so torch and torchvision reload.")
        get_ipython().kernel.do_shutdown(restart=True)

In [3]:
import pandas as pd
from src.utils import run

def show(name):
    overall = pd.read_csv("results/overall_metrics.csv").query("model_name == @name")
    detail = pd.read_csv("results/metrics.csv").query("model_name == @name")
    display(overall)
    display(detail)

## Local GPU: Qwen3-VL-2B, 4-bit

In [4]:
run("qwen3-vl-2b_4bit_local")
show("qwen3-vl-2b_4bit_local")

/home/rakesh/Downloads/ShortTok/3.ObjectDetection/ObjectDetection/.venv/lib/python3.12/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
Loading weights: 100%|██████████| 625/625 [00:04<00:00, 136.21it/s]
qwen3-vl-2b_4bit_local ecommerce:   0%|          | 0/38 [00:00<?, ?it/s][transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
/home/rakesh/Downloads/ShortTok/3.ObjectDetection/ObjectDetection/.venv/lib/python3.12/site-packages/transformers/models/qwen2_vl/image_processing_qwen2_vl.py:129: FutureWarning: Passing `min_pixels` and `max_pixels` to a processor call is deprecated and will be removed in v5.23. Pass in `size={'longest_edge': xxx, 'shortest_edge': xxx} to override the target size.`
  warnings.warn(
qwen3-vl-2b_4bit_local ecommerce:   3%|▎         | 1/38 [00:02<01:26,  2.33s/it][transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`

ecommerce A_black_coffee_mug_on_an_office_desk_with_a_blurred_laptop_in_the_background.jpg {'foreground': 'coffee_mug', 'background': '', 'relation': 'object_with_background'} 2.33s

qwen3-vl-2b_4bit_local ecommerce:   5%|▌         | 2/38 [00:03<00:55,  1.56s/it][transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`

ecommerce a_camera_is_attached_to_a_tripod_with_a_mountain_in_the_background.jpg {'foreground': 'camera', 'background': 'urban_architecture', 'relation': 'object_with_background'} 1.01s

qwen3-vl-2b_4bit_local ecommerce:   8%|▊         | 3/38 [00:04<00:47,  1.36s/it][transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`

ecommerce a_camera_on_a_tripod_with_a_mountain_in_the_background.jpg {'foreground': 'camera', 'background': 'mountain', 'relation': 'object_with_background'} 1.13s

qwen3-vl-2b_4bit_local ecommerce:  11%|█         | 4/38 [00:05<00:42,  1.24s/it][transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`

ecommerce A_close_up_shot_of_a_fountain_pen_with_an_ink_bottle_highlighted_by_warm_bokeh_lights_in_the_background.jpg {'foreground': 'pen', 'background': 'blurred_lights', 'relation': 'object_with_background'} 1.05s

qwen3-vl-2b_4bit_local ecommerce:  13%|█▎        | 5/38 [00:06<00:39,  1.18s/it][transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`

ecommerce A_hand_holds_a_mushroom_themed_cup_indoors_focusing_on_coziness_with_a_blurred_screen_in_the_background.jpg {'foreground': 'coffee_mug', 'background': 'blurred_laptop', 'relation': 'object_with_background'} 1.09s

qwen3-vl-2b_4bit_local ecommerce:  16%|█▌        | 6/38 [00:07<00:36,  1.14s/it][transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`

ecommerce A_hiking_backpack_resting_on_rocky_terrain_with_Tatra_Mountains_in_the_background.jpg {'foreground': 'backpack', 'background': 'mountain', 'relation': 'object_with_background'} 1.04s

qwen3-vl-2b_4bit_local ecommerce:  18%|█▊        | 7/38 [00:08<00:33,  1.08s/it][transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`

ecommerce A_kettle_on_the_stove_with_a_teenage_boy_reading_a_book_in_the_background.jpg {'foreground': 'kettle', 'background': '', 'relation': 'object_with_background'} 0.96s

qwen3-vl-2b_4bit_local ecommerce:  21%|██        | 8/38 [00:09<00:31,  1.04s/it][transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`

ecommerce A_Mobile_phone_charging_on_a_marble_table_with_a_pen_wallet_and_note_book_in_the_background.jpg {'foreground': 'phone', 'background': '', 'relation': 'object_with_background'} 0.94s

qwen3-vl-2b_4bit_local ecommerce:  24%|██▎       | 9/38 [00:10<00:30,  1.05s/it][transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`

ecommerce A_person_holding_up_a_pair_of_sunglasses_with_the_ocean_in_the_background.jpg {'foreground': 'sunglasses', 'background': 'ocean', 'relation': 'object_with_background'} 1.08s

qwen3-vl-2b_4bit_local ecommerce:  26%|██▋       | 10/38 [00:11<00:30,  1.07s/it][transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`

ecommerce A_red_mug_on_a_coaster_with_a_blurred_person_in_the_background_indoors.jpg {'foreground': 'coffee_mug', 'background': 'blurred_lights', 'relation': 'object_with_background'} 1.12s

qwen3-vl-2b_4bit_local ecommerce:  29%|██▉       | 11/38 [00:12<00:29,  1.10s/it][transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`

ecommerce A_smartphone_capturing_a_scenic_view_of_a_pebble_beach_with_blurred_hills_in_the_background.jpg {'foreground': 'phone', 'background': 'ocean', 'relation': 'object_with_background'} 1.15s

qwen3-vl-2b_4bit_local ecommerce:  32%|███▏      | 12/38 [00:14<00:28,  1.11s/it][transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`

ecommerce A_striped_mug_in_focus_with_a_warm_artistic_bokeh_effect_in_the_background.jpg {'foreground': 'coffee_mug', 'background': 'blurred_lights', 'relation': 'object_with_background'} 1.14s

qwen3-vl-2b_4bit_local ecommerce:  34%|███▍      | 13/38 [00:15<00:27,  1.12s/it][transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`

ecommerce A_vintage_camera_on_a_table_with_a_blurred_woman_in_the_background_holding_her_head.jpg {'foreground': 'camera', 'background': 'woman', 'relation': 'object_with_background'} 1.13s

qwen3-vl-2b_4bit_local ecommerce:  37%|███▋      | 14/38 [00:16<00:26,  1.12s/it][transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`

ecommerce Artistic_shot_of_a_vintage_camera_with_blurred_digital_images_in_the_background.jpg {'foreground': 'camera', 'background': '', 'relation': 'object_with_background'} 1.13s

qwen3-vl-2b_4bit_local ecommerce:  39%|███▉      | 15/38 [00:17<00:25,  1.10s/it][transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`

ecommerce Bright_yellow_mug_placed_on_concrete_with_blurred_urban_architecture_in_the_background.jpg {'foreground': 'coffee_mug', 'background': 'urban_architecture', 'relation': 'object_with_background'} 1.06s

qwen3-vl-2b_4bit_local ecommerce:  42%|████▏     | 16/38 [00:18<00:23,  1.08s/it][transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`

ecommerce Camera_on_log_with_snowy_mountains_in_background.jpg {'foreground': 'camera', 'background': 'mountain', 'relation': 'object_with_background'} 1.01s

qwen3-vl-2b_4bit_local ecommerce:  45%|████▍     | 17/38 [00:19<00:22,  1.06s/it][transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`

ecommerce Camera_on_tripod_capturing_a_cityscape_at_night_with_blurred_lights_in_the_background.jpg {'foreground': 'camera', 'background': 'blurred_lights', 'relation': 'object_with_background'} 1.01s

qwen3-vl-2b_4bit_local ecommerce:  47%|████▋     | 18/38 [00:20<00:20,  1.03s/it][transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`

ecommerce Close_up_of_a_bar_of_green_soap_with_a_blank_white_label_resting_on_a_gray_surface_with_a_white_towel_in_the_background.jpg {'foreground': 'soap', 'background': 'towel', 'relation': 'object_with_background'} 0.95s

qwen3-vl-2b_4bit_local ecommerce:  50%|█████     | 19/38 [00:21<00:19,  1.05s/it][transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`

ecommerce Close_up_of_a_decorative_Santa_mug_with_a_Christmas_tree_bokeh_in_the_background.jpg {'foreground': 'coffee_mug', 'background': 'blurred_lights', 'relation': 'object_with_background'} 1.10s

qwen3-vl-2b_4bit_local ecommerce:  53%|█████▎    | 20/38 [00:22<00:18,  1.03s/it][transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`

ecommerce Close_up_of_a_DSLR_camera_on_a_desk_in_a_modern_office_setting_with_people_in_the_background.jpg {'foreground': 'camera', 'background': 'people', 'relation': 'object_with_background'} 1.00s

qwen3-vl-2b_4bit_local ecommerce:  55%|█████▌    | 21/38 [00:23<00:17,  1.02s/it][transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`

ecommerce Close_up_of_a_professional_DSLR_camera_with_people_blurred_in_the_background.jpg {'foreground': 'camera', 'background': 'people', 'relation': 'object_with_background'} 0.99s

qwen3-vl-2b_4bit_local ecommerce:  58%|█████▊    | 22/38 [00:24<00:16,  1.04s/it][transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`

ecommerce Close_up_of_a_vintage_camera_on_a_café_table_with_a_dessert_in_the_background.jpg {'foreground': 'camera', 'background': 'dessert', 'relation': ''} 1.07s

qwen3-vl-2b_4bit_local ecommerce:  61%|██████    | 23/38 [00:25<00:15,  1.01s/it][transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`

ecommerce Close_up_of_alarm_clock_with_man_sleeping_in_the_background_Cape_Town_South_Africa.jpg {'foreground': 'alarm_clock', 'background': 'man', 'relation': 'object_with_background'} 0.94s

qwen3-vl-2b_4bit_local ecommerce:  63%|██████▎   | 24/38 [00:26<00:13,  1.01it/s][transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`

ecommerce Close_up_of_water_bottle_in_locker_room_with_an_athlete_in_the_background.jpg {'foreground': 'water_bottle', 'background': 'man', 'relation': 'object_with_background'} 0.96s

qwen3-vl-2b_4bit_local ecommerce:  66%|██████▌   | 25/38 [00:27<00:12,  1.00it/s][transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`

ecommerce Elegant_black_perfume_bottle_placed_on_a_textured_surface_with_vibrant_flowers_in_the_background_during_daylight.jpg {'foreground': 'perfume_bottle', 'background': 'flowers', 'relation': 'object_with_background'} 1.01s

qwen3-vl-2b_4bit_local ecommerce:  68%|██████▊   | 26/38 [00:28<00:12,  1.03s/it][transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`

ecommerce Flower_vase_on_window_sill_with_father_and_son_in_background.jpg {'foreground': 'flower_vase', 'background': 'man', 'relation': 'object_with_background'} 1.11s

qwen3-vl-2b_4bit_local ecommerce:  71%|███████   | 27/38 [00:29<00:11,  1.04s/it][transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`

ecommerce Golden_sunglasses_rest_on_a_table_by_the_beach_with_a_serene_sunset_and_palm_trees_in_the_background.jpg {'foreground': 'sunglasses', 'background': 'ocean', 'relation': 'object_with_background'} 1.05s

qwen3-vl-2b_4bit_local ecommerce:  74%|███████▎  | 28/38 [00:30<00:10,  1.04s/it][transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`

ecommerce Hand_holding_a_coffee_cup_at_night_with_blurred_city_lights_in_the_background.jpg {'foreground': 'coffee_mug', 'background': 'blurred_lights', 'relation': 'object_with_background'} 1.05s

qwen3-vl-2b_4bit_local ecommerce:  76%|███████▋  | 29/38 [00:31<00:09,  1.05s/it][transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`

ecommerce Laptop_on_wooden_table_in_a_loft_flat_with_man_at_the_window_in_background.jpg {'foreground': 'laptop', 'background': 'man', 'relation': 'object_with_background'} 1.08s

qwen3-vl-2b_4bit_local ecommerce:  79%|███████▉  | 30/38 [00:32<00:08,  1.03s/it][transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`

ecommerce Notebook_and_coffee_cup_in_modern_informal_office_with_man_and_woman_in_background.jpg {'foreground': 'coffee_mug', 'background': 'people', 'relation': 'object_with_background'} 0.96s

qwen3-vl-2b_4bit_local ecommerce:  82%|████████▏ | 31/38 [00:33<00:07,  1.00s/it][transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`

ecommerce Open_book_with_bookshelf_in_the_background.jpg {'foreground': 'book', 'background': 'bookshelf', 'relation': 'object_with_background'} 0.94s

qwen3-vl-2b_4bit_local ecommerce:  84%|████████▍ | 32/38 [00:34<00:06,  1.03s/it][transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`

ecommerce Red_lentils_in_glass_jar_with_cooking_oil_bottle_and_woman_in_background_at_store.jpg {'foreground': 'jar', 'background': 'bookshelf', 'relation': 'object_with_background'} 1.08s

qwen3-vl-2b_4bit_local ecommerce:  87%|████████▋ | 33/38 [00:35<00:05,  1.05s/it][transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`

ecommerce Red_mug_with_bokeh_Christmas_lights_in_the_background_evoking_holiday_warmth_and_coziness.jpg {'foreground': 'coffee_mug', 'background': 'blurred_lights', 'relation': 'object_with_background'} 1.11s

qwen3-vl-2b_4bit_local ecommerce:  89%|████████▉ | 34/38 [00:36<00:04,  1.06s/it][transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`

ecommerce Shaker_bottle_with_woman_working_out_in_the_background.jpg {'foreground': 'water_bottle', 'background': 'blurred_lights', 'relation': 'object_with_background'} 1.08s

qwen3-vl-2b_4bit_local ecommerce:  92%|█████████▏| 35/38 [00:38<00:03,  1.08s/it][transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`

ecommerce Stylish_golden_glasses_with_colorful_bokeh_of_Dhaka_nightlife_in_the_background.jpg {'foreground': 'sunglasses', 'background': 'blurred_lights', 'relation': 'object_with_background'} 1.11s

qwen3-vl-2b_4bit_local ecommerce:  95%|█████████▍| 36/38 [00:39<00:02,  1.06s/it][transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`

ecommerce Stylish_handbag_with_a_horse_in_the_background.jpg {'foreground': 'handbag', 'background': 'horse', 'relation': 'object_with_background'} 1.01s

qwen3-vl-2b_4bit_local ecommerce:  97%|█████████▋| 37/38 [00:40<00:01,  1.06s/it][transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`

ecommerce Tortoiseshell_sunglasses_resting_on_a_sandy_beach_with_ocean_waves_in_the_background.jpg {'foreground': 'sunglasses', 'background': 'ocean', 'relation': 'object_with_background'} 1.06s

qwen3-vl-2b_4bit_local ecommerce: 100%|██████████| 38/38 [00:41<00:00,  1.08s/it]

ecommerce White_lamp_sits_in_foreground_adorned_with_silver_snowflake_ornament_and_unrecognizable_woman_in_yellow_in_background_adjusting_decorations_on_rwindow.jpg {'foreground': 'lamp', 'background': 'man', 'relation': 'object_with_background'} 0.92s

qwen3-vl-2b_4bit_local news:   0%|          | 0/15 [00:00<?, ?it/s][transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
qwen3-vl-2b_4bit_local news:   7%|▋         | 1/15 [00:00<00:13,  1.01it/s][transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`

news Barack_Obama_at_Antalya.jpg {'foreground': 'Joe_Biden', 'background': 'Antalya', 'relation': 'people_at_event'} 0.98s

qwen3-vl-2b_4bit_local news:  13%|█▎        | 2/15 [00:01<00:13,  1.00s/it][transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`

news Barack_Obama_at_United_Nations.jpg {'foreground': 'Barack_Obama', 'background': 'United_Nations', 'relation': 'people_at_event'} 1.01s

qwen3-vl-2b_4bit_local news:  20%|██        | 3/15 [00:03<00:13,  1.09s/it][transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`

news Barack_Obama_at_White_House_Correspondents_Dinner.jpg {'foreground': 'Barack_Obama', 'background': 'White_House_Correspondents_Dinner', 'relation': ''} 1.20s

qwen3-vl-2b_4bit_local news:  27%|██▋       | 4/15 [00:04<00:12,  1.11s/it][transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`

news Ben_Affleck_at_Argo_press_junket.jpg {'foreground': 'Ben_Affleck', 'background': 'Argo_press_junket', 'relation': 'people_at_event'} 1.14s

qwen3-vl-2b_4bit_local news:  33%|███▎      | 5/15 [00:05<00:11,  1.12s/it][transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`

news Brad_Pitt_at_Venice_Film_Festival.jpg {'foreground': 'Brad_Pitt', 'background': 'Venice_Film_Festival', 'relation': 'people_at_event'} 1.13s

qwen3-vl-2b_4bit_local news:  40%|████      | 6/15 [00:06<00:09,  1.08s/it][transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`

news Donald_Trump_at_NRCC.jpg {'foreground': 'Donald_Trump', 'background': 'NRCC', 'relation': 'people_at_event'} 1.01s

qwen3-vl-2b_4bit_local news:  47%|████▋     | 7/15 [00:08<00:11,  1.46s/it][transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`

news Donald_Trump_at_Oval_Office2.jpg {'foreground': 'Donald_Trump', 'background': 'Florida', 'relation': 'people_at_event'} 2.23s

qwen3-vl-2b_4bit_local news:  53%|█████▎    | 8/15 [00:13<00:17,  2.49s/it][transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`

news Donald_Trump_at_Oval_Office3.jpg {'foreground': 'Donald_Trump', 'background': 'White_House', 'relation': ''} 4.69s

qwen3-vl-2b_4bit_local news:  60%|██████    | 9/15 [00:14<00:12,  2.04s/it][transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`

news Donald_Trump_at_Panama_City.jpg {'foreground': 'Donald_Trump', 'background': 'White_House', 'relation': 'people_at_event'} 1.05s

qwen3-vl-2b_4bit_local news:  67%|██████▋   | 10/15 [00:15<00:08,  1.73s/it][transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`

news Donald_Trump_at_White_House9.jpg {'foreground': 'Donald_Trump', 'background': 'White_House', 'relation': 'people_at_location'} 1.02s

qwen3-vl-2b_4bit_local news:  73%|███████▎  | 11/15 [00:16<00:06,  1.51s/it][transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`

news Joe_Biden_at_Buffalo.jpg {'foreground': 'Joe_Biden', 'background': 'White_House', 'relation': 'people_at_event'} 1.01s

qwen3-vl-2b_4bit_local news:  80%|████████  | 12/15 [00:17<00:04,  1.36s/it][transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`

news Joe_Biden_at_Oval_Office.jpg {'foreground': 'Joe_Biden', 'background': 'White_House', 'relation': 'people_at_location'} 1.03s

qwen3-vl-2b_4bit_local news:  87%|████████▋ | 13/15 [00:18<00:02,  1.30s/it][transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`

news Joe_Biden_at_State_of_the_Union.jpg {'foreground': 'Joe_Biden', 'background': 'White_House', 'relation': 'people_at_event'} 1.16s

qwen3-vl-2b_4bit_local news:  93%|█████████▎| 14/15 [00:19<00:01,  1.20s/it][transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`

news Joe_Biden_at_White_House_Correspondents_Dinner.jpg {'foreground': 'Joe_Biden', 'background': 'White_House', 'relation': 'people_at_location'} 0.97s

qwen3-vl-2b_4bit_local news: 100%|██████████| 15/15 [00:20<00:00,  1.38s/it]

news Mr_Bezos_at_Florida.jpg {'foreground': 'Jeff_Bezos', 'background': 'White_House', 'relation': 'people_at_event'} 1.06s
1.16s/image

,model_name,source,acc,micro_f1,macro_f1,latency (s),cost ($/1k images)
0,qwen3-vl-2b_4bit_local,open-source,0.811,0.83,0.768,1.164,0.0

,model_name,ecom_fg_acc,ecom_fg_micro_f1,ecom_fg_macro_f1,ecom_bg_acc,ecom_bg_micro_f1,ecom_bg_macro_f1,ecom_rel_acc,ecom_rel_micro_f1,ecom_rel_macro_f1,...,ecom_acc,ecom_micro_f1,ecom_macro_f1,news_acc,news_micro_f1,news_macro_f1,acc,micro_f1,macro_f1,latency (s)
0,qwen3-vl-2b_4bit_local,0.974,0.974,0.941,0.737,0.778,0.741,0.974,0.987,0.987,...,0.895,0.915,0.858,0.6,0.614,0.621,0.811,0.83,0.768,1.164

## Colab GPU: Qwen3-VL-4B

In [4]:
run("qwen3-vl-4b_colab")
show("qwen3-vl-4b_colab")

/usr/local/lib/python3.13/dist-packages/huggingface_hub/utils/_auth.py:140: UserWarning:
Error while fetching `HF_TOKEN` secret value from your vault: 'Requesting secret HF_TOKEN timed out. Secrets can only be fetched when running from the Colab UI.'.
  warnings.warn(f"\nError while fetching `HF_TOKEN` secret value from your vault: '{str(e)}'.")

Loading weights:   0%|          | 0/713 [00:00<?, ?it/s]

qwen3-vl-4b_colab ecommerce:   0%|          | 0/38 [00:00<?, ?it/s][transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
/usr/local/lib/python3.13/dist-packages/transformers/models/qwen2_vl/image_processing_qwen2_vl.py:129: FutureWarning: Passing `min_pixels` and `max_pixels` to a processor call is deprecated and will be removed in v5.23. Pass in `size={'longest_edge': xxx, 'shortest_edge': xxx} to override the target size.`
  warnings.warn(
qwen3-vl-4b_colab ecommerce:   3%|▎         | 1/38 [00:04<02:55,  4.74s/it][transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`

ecommerce A_black_coffee_mug_on_an_office_desk_with_a_blurred_laptop_in_the_background.jpg {'relation': 'object_with_background', 'foreground': 'coffee_mug', 'background': 'blurred_laptop'} 4.74s

qwen3-vl-4b_colab ecommerce:   5%|▌         | 2/38 [00:08<02:20,  3.91s/it][transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`

ecommerce a_camera_is_attached_to_a_tripod_with_a_mountain_in_the_background.jpg {'relation': 'object_with_background', 'foreground': 'camera', 'background': 'mountain'} 3.33s

qwen3-vl-4b_colab ecommerce:   8%|▊         | 3/38 [00:11<02:08,  3.67s/it][transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`

ecommerce a_camera_on_a_tripod_with_a_mountain_in_the_background.jpg {'relation': 'object_with_background', 'foreground': 'camera', 'background': 'mountain'} 3.38s

qwen3-vl-4b_colab ecommerce:  11%|█         | 4/38 [00:14<02:01,  3.58s/it][transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`

ecommerce A_close_up_shot_of_a_fountain_pen_with_an_ink_bottle_highlighted_by_warm_bokeh_lights_in_the_background.jpg {'relation': 'object_with_background', 'foreground': 'pen', 'background': 'blurred_lights'} 3.43s

qwen3-vl-4b_colab ecommerce:  13%|█▎        | 5/38 [00:18<01:57,  3.57s/it][transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`

ecommerce A_hand_holds_a_mushroom_themed_cup_indoors_focusing_on_coziness_with_a_blurred_screen_in_the_background.jpg {'relation': 'object_with_background', 'foreground': 'coffee_mug', 'background': 'blurred_laptop'} 3.55s

qwen3-vl-4b_colab ecommerce:  16%|█▌        | 6/38 [00:21<01:52,  3.52s/it][transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`

ecommerce A_hiking_backpack_resting_on_rocky_terrain_with_Tatra_Mountains_in_the_background.jpg {'relation': 'object_with_background', 'foreground': 'backpack', 'background': 'mountain'} 3.42s

qwen3-vl-4b_colab ecommerce:  18%|█▊        | 7/38 [00:25<01:46,  3.44s/it][transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`

ecommerce A_kettle_on_the_stove_with_a_teenage_boy_reading_a_book_in_the_background.jpg {'relation': 'object_with_background', 'foreground': 'kettle', 'background': 'man'} 3.26s

qwen3-vl-4b_colab ecommerce:  21%|██        | 8/38 [00:28<01:42,  3.40s/it][transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`

ecommerce A_Mobile_phone_charging_on_a_marble_table_with_a_pen_wallet_and_note_book_in_the_background.jpg {'relation': 'object_with_background', 'foreground': 'phone', 'background': 'blurred_laptop'} 3.32s

qwen3-vl-4b_colab ecommerce:  24%|██▎       | 9/38 [00:32<01:40,  3.45s/it][transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`

ecommerce A_person_holding_up_a_pair_of_sunglasses_with_the_ocean_in_the_background.jpg {'relation': 'object_with_background', 'foreground': 'sunglasses', 'background': 'ocean'} 3.55s

qwen3-vl-4b_colab ecommerce:  26%|██▋       | 10/38 [00:35<01:37,  3.48s/it][transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`

ecommerce A_red_mug_on_a_coaster_with_a_blurred_person_in_the_background_indoors.jpg {'relation': 'object_with_background', 'foreground': 'coffee_mug', 'background': 'blurred_laptop'} 3.53s

qwen3-vl-4b_colab ecommerce:  29%|██▉       | 11/38 [00:38<01:33,  3.45s/it][transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`

ecommerce A_smartphone_capturing_a_scenic_view_of_a_pebble_beach_with_blurred_hills_in_the_background.jpg {'relation': 'object_with_background', 'foreground': 'phone', 'background': 'ocean'} 3.39s

qwen3-vl-4b_colab ecommerce:  32%|███▏      | 12/38 [00:42<01:31,  3.50s/it][transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`

ecommerce A_striped_mug_in_focus_with_a_warm_artistic_bokeh_effect_in_the_background.jpg {'relation': 'object_with_background', 'foreground': 'coffee_mug', 'background': 'blurred_lights'} 3.61s

qwen3-vl-4b_colab ecommerce:  34%|███▍      | 13/38 [00:45<01:26,  3.47s/it][transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`

ecommerce A_vintage_camera_on_a_table_with_a_blurred_woman_in_the_background_holding_her_head.jpg {'relation': 'object_with_background', 'foreground': 'camera', 'background': 'woman'} 3.38s

qwen3-vl-4b_colab ecommerce:  37%|███▋      | 14/38 [00:49<01:23,  3.48s/it][transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`

ecommerce Artistic_shot_of_a_vintage_camera_with_blurred_digital_images_in_the_background.jpg {'relation': 'object_with_background', 'foreground': 'camera', 'background': 'blurred_laptop'} 3.52s

qwen3-vl-4b_colab ecommerce:  39%|███▉      | 15/38 [00:53<01:20,  3.51s/it][transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`

ecommerce Bright_yellow_mug_placed_on_concrete_with_blurred_urban_architecture_in_the_background.jpg {'relation': 'object_with_background', 'foreground': 'coffee_mug', 'background': 'urban_architecture'} 3.56s

qwen3-vl-4b_colab ecommerce:  42%|████▏     | 16/38 [00:56<01:16,  3.48s/it][transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`

ecommerce Camera_on_log_with_snowy_mountains_in_background.jpg {'relation': 'object_with_background', 'foreground': 'camera', 'background': 'mountain'} 3.41s

qwen3-vl-4b_colab ecommerce:  45%|████▍     | 17/38 [00:59<01:12,  3.47s/it][transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`

ecommerce Camera_on_tripod_capturing_a_cityscape_at_night_with_blurred_lights_in_the_background.jpg {'relation': 'object_with_background', 'foreground': 'camera', 'background': 'blurred_lights'} 3.45s

qwen3-vl-4b_colab ecommerce:  47%|████▋     | 18/38 [01:03<01:09,  3.45s/it][transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`

ecommerce Close_up_of_a_bar_of_green_soap_with_a_blank_white_label_resting_on_a_gray_surface_with_a_white_towel_in_the_background.jpg {'relation': 'object_with_background', 'foreground': 'soap', 'background': 'towel'} 3.39s

qwen3-vl-4b_colab ecommerce:  50%|█████     | 19/38 [01:06<01:06,  3.50s/it][transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`

ecommerce Close_up_of_a_decorative_Santa_mug_with_a_Christmas_tree_bokeh_in_the_background.jpg {'relation': 'object_with_background', 'foreground': 'coffee_mug', 'background': 'blurred_lights'} 3.61s

qwen3-vl-4b_colab ecommerce:  53%|█████▎    | 20/38 [01:10<01:03,  3.50s/it][transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`

ecommerce Close_up_of_a_DSLR_camera_on_a_desk_in_a_modern_office_setting_with_people_in_the_background.jpg {'relation': 'object_with_background', 'foreground': 'camera', 'background': 'blurred_lights'} 3.50s

qwen3-vl-4b_colab ecommerce:  55%|█████▌    | 21/38 [01:14<00:59,  3.52s/it][transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`

ecommerce Close_up_of_a_professional_DSLR_camera_with_people_blurred_in_the_background.jpg {'relation': 'object_with_background', 'foreground': 'camera', 'background': 'blurred_lights'} 3.56s

qwen3-vl-4b_colab ecommerce:  58%|█████▊    | 22/38 [01:17<00:55,  3.48s/it][transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`

ecommerce Close_up_of_a_vintage_camera_on_a_café_table_with_a_dessert_in_the_background.jpg {'relation': 'object_with_background', 'foreground': 'camera', 'background': 'dessert'} 3.38s

qwen3-vl-4b_colab ecommerce:  61%|██████    | 23/38 [01:20<00:51,  3.42s/it][transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`

ecommerce Close_up_of_alarm_clock_with_man_sleeping_in_the_background_Cape_Town_South_Africa.jpg {'relation': 'object_with_background', 'foreground': 'alarm_clock', 'background': 'man'} 3.29s

qwen3-vl-4b_colab ecommerce:  63%|██████▎   | 24/38 [01:24<00:47,  3.42s/it][transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`

ecommerce Close_up_of_water_bottle_in_locker_room_with_an_athlete_in_the_background.jpg {'relation': 'object_with_background', 'foreground': 'water_bottle', 'background': 'man'} 3.41s

qwen3-vl-4b_colab ecommerce:  66%|██████▌   | 25/38 [01:27<00:44,  3.40s/it][transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`

ecommerce Elegant_black_perfume_bottle_placed_on_a_textured_surface_with_vibrant_flowers_in_the_background_during_daylight.jpg {'relation': 'object_with_background', 'foreground': 'perfume_bottle', 'background': 'flowers'} 3.36s

qwen3-vl-4b_colab ecommerce:  68%|██████▊   | 26/38 [01:30<00:40,  3.38s/it][transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`

ecommerce Flower_vase_on_window_sill_with_father_and_son_in_background.jpg {'relation': 'object_with_background', 'foreground': 'flower_vase', 'background': 'man'} 3.31s

qwen3-vl-4b_colab ecommerce:  71%|███████   | 27/38 [01:34<00:37,  3.43s/it][transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`

ecommerce Golden_sunglasses_rest_on_a_table_by_the_beach_with_a_serene_sunset_and_palm_trees_in_the_background.jpg {'relation': 'object_with_background', 'foreground': 'sunglasses', 'background': 'ocean'} 3.56s

qwen3-vl-4b_colab ecommerce:  74%|███████▎  | 28/38 [01:37<00:34,  3.45s/it][transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`

ecommerce Hand_holding_a_coffee_cup_at_night_with_blurred_city_lights_in_the_background.jpg {'relation': 'object_with_background', 'foreground': 'coffee_mug', 'background': 'blurred_lights'} 3.48s

qwen3-vl-4b_colab ecommerce:  76%|███████▋  | 29/38 [01:41<00:30,  3.38s/it][transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`

ecommerce Laptop_on_wooden_table_in_a_loft_flat_with_man_at_the_window_in_background.jpg {'relation': 'object_with_background', 'foreground': 'laptop', 'background': 'man'} 3.21s

qwen3-vl-4b_colab ecommerce:  79%|███████▉  | 30/38 [01:44<00:26,  3.37s/it][transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`

ecommerce Notebook_and_coffee_cup_in_modern_informal_office_with_man_and_woman_in_background.jpg {'relation': 'object_with_background', 'foreground': 'coffee_mug', 'background': 'people'} 3.34s

qwen3-vl-4b_colab ecommerce:  82%|████████▏ | 31/38 [01:47<00:23,  3.33s/it][transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`

ecommerce Open_book_with_bookshelf_in_the_background.jpg {'relation': 'object_with_background', 'foreground': 'book', 'background': 'bookshelf'} 3.23s

qwen3-vl-4b_colab ecommerce:  84%|████████▍ | 32/38 [01:50<00:19,  3.28s/it][transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`

ecommerce Red_lentils_in_glass_jar_with_cooking_oil_bottle_and_woman_in_background_at_store.jpg {'relation': 'object_with_background', 'foreground': 'jar', 'background': 'woman'} 3.18s

qwen3-vl-4b_colab ecommerce:  87%|████████▋ | 33/38 [01:54<00:17,  3.42s/it][transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`

ecommerce Red_mug_with_bokeh_Christmas_lights_in_the_background_evoking_holiday_warmth_and_coziness.jpg {'relation': 'object_with_background', 'foreground': 'coffee_mug', 'background': 'blurred_lights'} 3.72s

qwen3-vl-4b_colab ecommerce:  89%|████████▉ | 34/38 [01:57<00:13,  3.42s/it][transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`

ecommerce Shaker_bottle_with_woman_working_out_in_the_background.jpg {'relation': 'object_with_background', 'foreground': 'water_bottle', 'background': 'blurred_lights'} 3.42s

qwen3-vl-4b_colab ecommerce:  92%|█████████▏| 35/38 [02:01<00:10,  3.46s/it][transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`

ecommerce Stylish_golden_glasses_with_colorful_bokeh_of_Dhaka_nightlife_in_the_background.jpg {'relation': 'object_with_background', 'foreground': 'sunglasses', 'background': 'blurred_lights'} 3.56s

qwen3-vl-4b_colab ecommerce:  95%|█████████▍| 36/38 [02:04<00:06,  3.46s/it][transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`

ecommerce Stylish_handbag_with_a_horse_in_the_background.jpg {'relation': 'object_with_background', 'foreground': 'handbag', 'background': 'horse'} 3.45s

qwen3-vl-4b_colab ecommerce:  97%|█████████▋| 37/38 [02:08<00:03,  3.46s/it][transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`

ecommerce Tortoiseshell_sunglasses_resting_on_a_sandy_beach_with_ocean_waves_in_the_background.jpg {'relation': 'object_with_background', 'foreground': 'sunglasses', 'background': 'ocean'} 3.46s

qwen3-vl-4b_colab ecommerce: 100%|██████████| 38/38 [02:11<00:00,  3.47s/it]

ecommerce White_lamp_sits_in_foreground_adorned_with_silver_snowflake_ornament_and_unrecognizable_woman_in_yellow_in_background_adjusting_decorations_on_rwindow.jpg {'relation': 'object_with_background', 'foreground': 'lamp', 'background': 'blurred_lights'} 3.36s

qwen3-vl-4b_colab news:   0%|          | 0/15 [00:00<?, ?it/s][transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
qwen3-vl-4b_colab news:   7%|▋         | 1/15 [00:03<00:47,  3.42s/it][transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`

news Barack_Obama_at_Antalya.jpg {'relation': 'people_at_event', 'foreground': 'Barack_Obama', 'background': 'Antalya'} 3.42s

qwen3-vl-4b_colab news:  13%|█▎        | 2/15 [00:06<00:44,  3.38s/it][transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`

news Barack_Obama_at_United_Nations.jpg {'relation': 'people_at_event', 'foreground': 'Barack_Obama', 'background': 'United_Nations'} 3.36s

qwen3-vl-4b_colab news:  20%|██        | 3/15 [00:10<00:42,  3.56s/it][transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`

news Barack_Obama_at_White_House_Correspondents_Dinner.jpg {'relation': 'people_at_event', 'foreground': 'Barack_Obama', 'background': 'White_House_Correspondents_Dinner'} 3.77s

qwen3-vl-4b_colab news:  27%|██▋       | 4/15 [00:14<00:40,  3.66s/it][transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`

news Ben_Affleck_at_Argo_press_junket.jpg {'relation': 'people_at_event', 'foreground': 'Ben_Affleck', 'background': 'Argo_press_junket'} 3.79s

qwen3-vl-4b_colab news:  33%|███▎      | 5/15 [00:18<00:36,  3.67s/it][transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`

news Brad_Pitt_at_Venice_Film_Festival.jpg {'relation': 'people_at_event', 'foreground': 'Brad_Pitt', 'background': 'Argo_press_junket'} 3.70s

qwen3-vl-4b_colab news:  40%|████      | 6/15 [00:21<00:32,  3.61s/it][transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`

news Donald_Trump_at_NRCC.jpg {'relation': 'people_at_event', 'foreground': 'Donald_Trump', 'background': 'NRCC'} 3.47s

qwen3-vl-4b_colab news:  47%|████▋     | 7/15 [00:25<00:28,  3.57s/it][transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`

news Donald_Trump_at_Oval_Office2.jpg {'relation': 'people_at_location', 'foreground': 'Donald_Trump', 'background': 'White_House'} 3.48s

qwen3-vl-4b_colab news:  53%|█████▎    | 8/15 [00:28<00:24,  3.53s/it][transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`

news Donald_Trump_at_Oval_Office3.jpg {'relation': 'people_at_location', 'foreground': 'Donald_Trump', 'background': 'White_House'} 3.43s

qwen3-vl-4b_colab news:  60%|██████    | 9/15 [00:31<00:21,  3.52s/it][transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`

news Donald_Trump_at_Panama_City.jpg {'relation': 'people_at_event', 'foreground': 'Donald_Trump', 'background': 'White_House'} 3.48s

qwen3-vl-4b_colab news:  67%|██████▋   | 10/15 [00:35<00:17,  3.50s/it][transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`

news Donald_Trump_at_White_House9.jpg {'relation': 'people_at_location', 'foreground': 'Donald_Trump', 'background': 'White_House'} 3.46s

qwen3-vl-4b_colab news:  73%|███████▎  | 11/15 [00:38<00:13,  3.42s/it][transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`

news Joe_Biden_at_Buffalo.jpg {'relation': 'people_at_location', 'foreground': 'Joe_Biden', 'background': 'White_House'} 3.23s

qwen3-vl-4b_colab news:  80%|████████  | 12/15 [00:42<00:10,  3.46s/it][transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`

news Joe_Biden_at_Oval_Office.jpg {'relation': 'people_at_location', 'foreground': 'Joe_Biden', 'background': 'White_House'} 3.54s

qwen3-vl-4b_colab news:  87%|████████▋ | 13/15 [00:45<00:07,  3.54s/it][transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`

news Joe_Biden_at_State_of_the_Union.jpg {'relation': 'people_at_event', 'foreground': 'Joe_Biden', 'background': 'State_of_the_Union'} 3.73s

qwen3-vl-4b_colab news:  93%|█████████▎| 14/15 [00:49<00:03,  3.46s/it][transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`

news Joe_Biden_at_White_House_Correspondents_Dinner.jpg {'relation': 'people_at_location', 'foreground': 'Joe_Biden', 'background': 'White_House'} 3.26s

qwen3-vl-4b_colab news: 100%|██████████| 15/15 [00:52<00:00,  3.52s/it]

news Mr_Bezos_at_Florida.jpg {'foreground': '', 'background': '', 'relation': ''} 3.57s
3.48s/image

,model_name,source,acc,micro_f1,macro_f1,latency (s),cost ($/1k images)
0,qwen3-vl-4b_colab,open-source,0.855,0.863,0.774,3.477,0

,model_name,ecom_fg_acc,ecom_fg_micro_f1,ecom_fg_macro_f1,ecom_bg_acc,ecom_bg_micro_f1,ecom_bg_macro_f1,ecom_rel_acc,ecom_rel_micro_f1,ecom_rel_macro_f1,...,ecom_acc,ecom_micro_f1,ecom_macro_f1,news_acc,news_micro_f1,news_macro_f1,acc,micro_f1,macro_f1,latency (s)
0,qwen3-vl-4b_colab,0.974,0.974,0.941,0.789,0.789,0.796,1.0,1.0,1.0,...,0.921,0.921,0.881,0.689,0.713,0.598,0.855,0.863,0.774,3.477

## Colab GPU: Qwen3-VL-8B, 4-bit

In [4]:
run("qwen3-vl-8b_4bit_colab")
show("qwen3-vl-8b_4bit_colab")

/usr/local/lib/python3.13/dist-packages/huggingface_hub/utils/_auth.py:140: UserWarning:
Error while fetching `HF_TOKEN` secret value from your vault: 'Requesting secret HF_TOKEN timed out. Secrets can only be fetched when running from the Colab UI.'.
  warnings.warn(f"\nError while fetching `HF_TOKEN` secret value from your vault: '{str(e)}'.")
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

config.json:   0%|          | 0.00/1.47k [00:00<?, ?B/s]

model.safetensors.index.json:   0%|          | 0.00/67.8k [00:00<?, ?B/s]

Downloading bytes:           |  0.00B

Reconstructing (incomplete total...): |          |  0.00B /  0.00B

Fetching 4 files:   0%|          | 0/4 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/750 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/269 [00:00<?, ?B/s]

preprocessor_config.json:   0%|          | 0.00/390 [00:00<?, ?B/s]

chat_template.json:   0%|          | 0.00/5.50k [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/10.9k [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/2.78M [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/1.67M [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/7.03M [00:00<?, ?B/s]

video_preprocessor_config.json:   0%|          | 0.00/385 [00:00<?, ?B/s]

qwen3-vl-8b_4bit_colab ecommerce:   0%|          | 0/38 [00:00<?, ?it/s][transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
/usr/local/lib/python3.13/dist-packages/transformers/models/qwen2_vl/image_processing_qwen2_vl.py:129: FutureWarning: Passing `min_pixels` and `max_pixels` to a processor call is deprecated and will be removed in v5.23. Pass in `size={'longest_edge': xxx, 'shortest_edge': xxx} to override the target size.`
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/bitsandbytes/backends/cuda/ops.py:957: UserWarning: inner dimension (4304) is not aligned for fast kernel with blocksize=64, falling back to slower implementation.
  warn(
qwen3-vl-8b_4bit_colab ecommerce:   3%|▎         | 1/38 [00:21<13:28, 21.86s/it][transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`

ecommerce A_black_coffee_mug_on_an_office_desk_with_a_blurred_laptop_in_the_background.jpg {'relation': 'object_with_background', 'foreground': 'coffee_mug', 'background': 'blurred_laptop'} 21.85s

qwen3-vl-8b_4bit_colab ecommerce:   5%|▌         | 2/38 [00:42<12:32, 20.90s/it][transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`

ecommerce a_camera_is_attached_to_a_tripod_with_a_mountain_in_the_background.jpg {'relation': 'object_with_background', 'foreground': 'camera', 'background': 'mountain'} 20.23s

qwen3-vl-8b_4bit_colab ecommerce:   8%|▊         | 3/38 [01:02<12:03, 20.66s/it][transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`

ecommerce a_camera_on_a_tripod_with_a_mountain_in_the_background.jpg {'relation': 'object_with_background', 'foreground': 'camera', 'background': 'mountain'} 20.37s

qwen3-vl-8b_4bit_colab ecommerce:  13%|█▎        | 5/38 [01:43<11:15, 20.47s/it][transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`

ecommerce A_hand_holds_a_mushroom_themed_cup_indoors_focusing_on_coziness_with_a_blurred_screen_in_the_background.jpg {'relation': 'object_with_background', 'foreground': 'coffee_mug', 'background': 'blurred_laptop'} 20.18s

qwen3-vl-8b_4bit_colab ecommerce:  16%|█▌        | 6/38 [02:03<10:50, 20.34s/it][transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`

ecommerce A_hiking_backpack_resting_on_rocky_terrain_with_Tatra_Mountains_in_the_background.jpg {'relation': 'object_with_background', 'foreground': 'backpack', 'background': 'mountain'} 20.07s

qwen3-vl-8b_4bit_colab ecommerce:  18%|█▊        | 7/38 [02:18<09:38, 18.65s/it][transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`

ecommerce A_kettle_on_the_stove_with_a_teenage_boy_reading_a_book_in_the_background.jpg {'relation': 'object_with_background', 'foreground': 'kettle', 'background': 'woman'} 15.18s

qwen3-vl-8b_4bit_colab ecommerce:  21%|██        | 8/38 [02:33<08:41, 17.39s/it][transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`

ecommerce A_Mobile_phone_charging_on_a_marble_table_with_a_pen_wallet_and_note_book_in_the_background.jpg {'relation': 'object_with_background', 'foreground': 'phone', 'background': 'pen'} 14.69s

qwen3-vl-8b_4bit_colab ecommerce:  24%|██▎       | 9/38 [02:53<08:50, 18.31s/it][transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`

ecommerce A_person_holding_up_a_pair_of_sunglasses_with_the_ocean_in_the_background.jpg {'relation': 'object_with_background', 'foreground': 'sunglasses', 'background': 'ocean'} 20.32s

qwen3-vl-8b_4bit_colab ecommerce:  26%|██▋       | 10/38 [03:13<08:51, 18.97s/it][transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`

ecommerce A_red_mug_on_a_coaster_with_a_blurred_person_in_the_background_indoors.jpg {'relation': 'object_with_background', 'foreground': 'coffee_mug', 'background': 'woman'} 20.45s

qwen3-vl-8b_4bit_colab ecommerce:  29%|██▉       | 11/38 [03:34<08:45, 19.44s/it][transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`

ecommerce A_smartphone_capturing_a_scenic_view_of_a_pebble_beach_with_blurred_hills_in_the_background.jpg {'relation': 'object_with_background', 'foreground': 'phone', 'background': 'mountain'} 20.52s

qwen3-vl-8b_4bit_colab ecommerce:  32%|███▏      | 12/38 [03:55<08:35, 19.82s/it][transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`

ecommerce A_striped_mug_in_focus_with_a_warm_artistic_bokeh_effect_in_the_background.jpg {'relation': 'object_with_background', 'foreground': 'coffee_mug', 'background': 'blurred_lights'} 20.68s

qwen3-vl-8b_4bit_colab ecommerce:  34%|███▍      | 13/38 [04:14<08:13, 19.75s/it][transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`

ecommerce A_vintage_camera_on_a_table_with_a_blurred_woman_in_the_background_holding_her_head.jpg {'relation': 'object_with_background', 'foreground': 'camera', 'background': 'woman'} 19.57s

qwen3-vl-8b_4bit_colab ecommerce:  37%|███▋      | 14/38 [04:35<08:01, 20.06s/it][transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`

ecommerce Artistic_shot_of_a_vintage_camera_with_blurred_digital_images_in_the_background.jpg {'relation': 'object_with_background', 'foreground': 'camera', 'background': 'blurred_laptop'} 20.77s

qwen3-vl-8b_4bit_colab ecommerce:  39%|███▉      | 15/38 [04:56<07:48, 20.37s/it][transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`

ecommerce Bright_yellow_mug_placed_on_concrete_with_blurred_urban_architecture_in_the_background.jpg {'relation': 'object_with_background', 'foreground': 'coffee_mug', 'background': 'urban_architecture'} 21.10s

qwen3-vl-8b_4bit_colab ecommerce:  42%|████▏     | 16/38 [05:17<07:32, 20.59s/it][transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`

ecommerce Camera_on_log_with_snowy_mountains_in_background.jpg {'relation': 'object_with_background', 'foreground': 'camera', 'background': 'mountain'} 21.09s

qwen3-vl-8b_4bit_colab ecommerce:  45%|████▍     | 17/38 [05:37<07:08, 20.38s/it][transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`

ecommerce Camera_on_tripod_capturing_a_cityscape_at_night_with_blurred_lights_in_the_background.jpg {'relation': 'object_with_background', 'foreground': 'camera', 'background': 'blurred_lights'} 19.89s

qwen3-vl-8b_4bit_colab ecommerce:  47%|████▋     | 18/38 [05:53<06:20, 19.04s/it][transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`

ecommerce Close_up_of_a_bar_of_green_soap_with_a_blank_white_label_resting_on_a_gray_surface_with_a_white_towel_in_the_background.jpg {'relation': 'object_with_background', 'foreground': 'soap', 'background': 'towel'} 15.92s

qwen3-vl-8b_4bit_colab ecommerce:  50%|█████     | 19/38 [06:14<06:12, 19.62s/it][transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`

ecommerce Close_up_of_a_decorative_Santa_mug_with_a_Christmas_tree_bokeh_in_the_background.jpg {'relation': 'object_with_background', 'foreground': 'coffee_mug', 'background': 'blurred_lights'} 20.97s

qwen3-vl-8b_4bit_colab ecommerce:  53%|█████▎    | 20/38 [06:34<05:57, 19.88s/it][transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`

ecommerce Close_up_of_a_DSLR_camera_on_a_desk_in_a_modern_office_setting_with_people_in_the_background.jpg {'relation': 'object_with_background', 'foreground': 'camera', 'background': 'people'} 20.48s

qwen3-vl-8b_4bit_colab ecommerce:  55%|█████▌    | 21/38 [06:55<05:40, 20.04s/it][transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`

ecommerce Close_up_of_a_professional_DSLR_camera_with_people_blurred_in_the_background.jpg {'relation': 'object_with_background', 'foreground': 'camera', 'background': 'people'} 20.39s

qwen3-vl-8b_4bit_colab ecommerce:  58%|█████▊    | 22/38 [07:15<05:19, 19.98s/it][transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`

ecommerce Close_up_of_a_vintage_camera_on_a_café_table_with_a_dessert_in_the_background.jpg {'relation': 'object_with_background', 'foreground': 'camera', 'background': 'dessert'} 19.85s

qwen3-vl-8b_4bit_colab ecommerce:  61%|██████    | 23/38 [07:30<04:37, 18.51s/it][transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`

ecommerce Close_up_of_alarm_clock_with_man_sleeping_in_the_background_Cape_Town_South_Africa.jpg {'relation': 'object_with_background', 'foreground': 'alarm_clock', 'background': 'people'} 15.08s

qwen3-vl-8b_4bit_colab ecommerce:  63%|██████▎   | 24/38 [07:45<04:05, 17.56s/it][transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`

ecommerce Close_up_of_water_bottle_in_locker_room_with_an_athlete_in_the_background.jpg {'relation': 'object_with_background', 'foreground': 'water_bottle', 'background': 'man'} 15.32s

qwen3-vl-8b_4bit_colab ecommerce:  66%|██████▌   | 25/38 [08:01<03:39, 16.89s/it][transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`

ecommerce Elegant_black_perfume_bottle_placed_on_a_textured_surface_with_vibrant_flowers_in_the_background_during_daylight.jpg {'relation': 'object_with_background', 'foreground': 'perfume_bottle', 'background': 'flowers'} 15.33s

qwen3-vl-8b_4bit_colab ecommerce:  68%|██████▊   | 26/38 [08:16<03:16, 16.40s/it][transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`

ecommerce Flower_vase_on_window_sill_with_father_and_son_in_background.jpg {'relation': 'object_with_background', 'foreground': 'flower_vase', 'background': 'man'} 15.25s

qwen3-vl-8b_4bit_colab ecommerce:  71%|███████   | 27/38 [08:36<03:13, 17.55s/it][transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`

ecommerce Golden_sunglasses_rest_on_a_table_by_the_beach_with_a_serene_sunset_and_palm_trees_in_the_background.jpg {'relation': 'object_with_background', 'foreground': 'sunglasses', 'background': 'ocean'} 20.22s

qwen3-vl-8b_4bit_colab ecommerce:  74%|███████▎  | 28/38 [08:52<02:50, 17.09s/it][transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`

ecommerce Hand_holding_a_coffee_cup_at_night_with_blurred_city_lights_in_the_background.jpg {'relation': 'object_with_background', 'foreground': 'coffee_mug', 'background': 'blurred_lights'} 16.01s

qwen3-vl-8b_4bit_colab ecommerce:  76%|███████▋  | 29/38 [09:07<02:28, 16.51s/it][transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`

ecommerce Laptop_on_wooden_table_in_a_loft_flat_with_man_at_the_window_in_background.jpg {'relation': 'object_with_background', 'foreground': 'laptop', 'background': 'urban_architecture'} 15.15s

qwen3-vl-8b_4bit_colab ecommerce:  79%|███████▉  | 30/38 [09:22<02:09, 16.16s/it][transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`

ecommerce Notebook_and_coffee_cup_in_modern_informal_office_with_man_and_woman_in_background.jpg {'relation': 'object_with_background', 'foreground': 'coffee_mug', 'background': 'people'} 15.33s

qwen3-vl-8b_4bit_colab ecommerce:  82%|████████▏ | 31/38 [09:37<01:50, 15.78s/it][transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`

ecommerce Open_book_with_bookshelf_in_the_background.jpg {'relation': 'object_with_background', 'foreground': 'book', 'background': 'bookshelf'} 14.89s

qwen3-vl-8b_4bit_colab ecommerce:  84%|████████▍ | 32/38 [09:52<01:32, 15.47s/it][transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`

ecommerce Red_lentils_in_glass_jar_with_cooking_oil_bottle_and_woman_in_background_at_store.jpg {'relation': 'object_with_background', 'foreground': 'jar', 'background': 'woman'} 14.76s

qwen3-vl-8b_4bit_colab ecommerce:  87%|████████▋ | 33/38 [10:13<01:25, 17.15s/it][transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`

ecommerce Red_mug_with_bokeh_Christmas_lights_in_the_background_evoking_holiday_warmth_and_coziness.jpg {'relation': 'object_with_background', 'foreground': 'coffee_mug', 'background': 'blurred_lights'} 21.05s

qwen3-vl-8b_4bit_colab ecommerce:  89%|████████▉ | 34/38 [10:28<01:06, 16.58s/it][transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`

ecommerce Shaker_bottle_with_woman_working_out_in_the_background.jpg {'relation': 'object_with_background', 'foreground': 'water_bottle', 'background': 'blurred_lights'} 15.25s

qwen3-vl-8b_4bit_colab ecommerce:  92%|█████████▏| 35/38 [10:49<00:53, 17.87s/it][transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`

ecommerce Stylish_golden_glasses_with_colorful_bokeh_of_Dhaka_nightlife_in_the_background.jpg {'relation': 'object_with_background', 'foreground': 'sunglasses', 'background': 'blurred_lights'} 20.86s

qwen3-vl-8b_4bit_colab ecommerce:  95%|█████████▍| 36/38 [11:10<00:37, 18.63s/it][transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`

ecommerce Stylish_handbag_with_a_horse_in_the_background.jpg {'relation': 'object_with_background', 'foreground': 'handbag', 'background': 'horse'} 20.42s

qwen3-vl-8b_4bit_colab ecommerce:  97%|█████████▋| 37/38 [11:30<00:19, 19.26s/it][transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`

ecommerce Tortoiseshell_sunglasses_resting_on_a_sandy_beach_with_ocean_waves_in_the_background.jpg {'relation': 'object_with_background', 'foreground': 'sunglasses', 'background': 'ocean'} 20.72s

qwen3-vl-8b_4bit_colab ecommerce: 100%|██████████| 38/38 [11:45<00:00, 18.58s/it]

ecommerce White_lamp_sits_in_foreground_adorned_with_silver_snowflake_ornament_and_unrecognizable_woman_in_yellow_in_background_adjusting_decorations_on_rwindow.jpg {'relation': 'object_with_background', 'foreground': 'lamp', 'background': 'woman'} 14.92s

qwen3-vl-8b_4bit_colab news:   0%|          | 0/15 [00:00<?, ?it/s][transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
qwen3-vl-8b_4bit_colab news:   7%|▋         | 1/15 [00:08<01:53,  8.14s/it][transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`

news Barack_Obama_at_Antalya.jpg {'relation': 'people_at_event', 'foreground': 'Joe_Biden', 'background': 'Antalya'} 8.13s

qwen3-vl-8b_4bit_colab news:  13%|█▎        | 2/15 [00:15<01:43,  7.95s/it][transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`

news Barack_Obama_at_United_Nations.jpg {'relation': 'people_at_event', 'foreground': 'Joe_Biden', 'background': 'United_Nations'} 7.81s

qwen3-vl-8b_4bit_colab news:  20%|██        | 3/15 [00:26<01:47,  8.99s/it][transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`

news Barack_Obama_at_White_House_Correspondents_Dinner.jpg {'relation': 'people_at_event', 'foreground': 'Joe_Biden', 'background': 'White_House_Correspondents_Dinner'} 10.23s

qwen3-vl-8b_4bit_colab news:  27%|██▋       | 4/15 [00:47<02:30, 13.66s/it][transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`

news Ben_Affleck_at_Argo_press_junket.jpg {'relation': 'people_at_event', 'foreground': 'Ben_Affleck', 'background': 'Argo_press_junket'} 20.82s

qwen3-vl-8b_4bit_colab news:  33%|███▎      | 5/15 [01:07<02:41, 16.13s/it][transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`

news Brad_Pitt_at_Venice_Film_Festival.jpg {'relation': 'people_at_event', 'foreground': 'Brad_Pitt', 'background': 'Venice_Film_Festival'} 20.50s

qwen3-vl-8b_4bit_colab news:  40%|████      | 6/15 [01:25<02:29, 16.66s/it][transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`

news Donald_Trump_at_NRCC.jpg {'relation': 'people_at_event', 'foreground': 'Donald_Trump', 'background': 'NRCC'} 17.69s

qwen3-vl-8b_4bit_colab news:  47%|████▋     | 7/15 [01:42<02:15, 16.90s/it][transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`

news Donald_Trump_at_Oval_Office2.jpg {'relation': 'people_at_event', 'foreground': 'Donald_Trump', 'background': 'White_House'} 17.39s

qwen3-vl-8b_4bit_colab news:  53%|█████▎    | 8/15 [02:00<01:59, 17.10s/it][transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`

news Donald_Trump_at_Oval_Office3.jpg {'relation': 'people_at_location', 'foreground': 'Donald_Trump', 'background': 'White_House'} 17.51s

qwen3-vl-8b_4bit_colab news:  60%|██████    | 9/15 [02:17<01:43, 17.23s/it][transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`

news Donald_Trump_at_Panama_City.jpg {'relation': 'people_at_event', 'foreground': 'Donald_Trump', 'background': 'White_House'} 17.52s

qwen3-vl-8b_4bit_colab news:  67%|██████▋   | 10/15 [02:35<01:27, 17.53s/it][transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`

news Donald_Trump_at_White_House9.jpg {'relation': 'people_at_location', 'foreground': 'Donald_Trump', 'background': 'White_House'} 18.18s

qwen3-vl-8b_4bit_colab news:  73%|███████▎  | 11/15 [02:44<00:58, 14.73s/it][transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`

news Joe_Biden_at_Buffalo.jpg {'relation': 'people_at_event', 'foreground': 'Joe_Biden', 'background': 'White_House_Correspondents_Dinner'} 8.38s

qwen3-vl-8b_4bit_colab news:  80%|████████  | 12/15 [03:04<00:49, 16.37s/it][transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`

news Joe_Biden_at_Oval_Office.jpg {'relation': 'people_at_location', 'foreground': 'Joe_Biden', 'background': 'White_House'} 20.14s

qwen3-vl-8b_4bit_colab news:  87%|████████▋ | 13/15 [03:24<00:34, 17.47s/it][transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`

news Joe_Biden_at_State_of_the_Union.jpg {'relation': 'people_at_event', 'foreground': 'Joe_Biden', 'background': 'State_of_the_Union'} 19.97s

qwen3-vl-8b_4bit_colab news:  93%|█████████▎| 14/15 [03:32<00:14, 14.71s/it][transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`

news Joe_Biden_at_White_House_Correspondents_Dinner.jpg {'relation': 'people_at_event', 'foreground': 'Joe_Biden', 'background': 'White_House_Correspondents_Dinner'} 8.33s

qwen3-vl-8b_4bit_colab news: 100%|██████████| 15/15 [03:53<00:00, 15.56s/it]

news Mr_Bezos_at_Florida.jpg {'foreground': '', 'background': '', 'relation': ''} 20.75s
17.72s/image

,model_name,source,acc,micro_f1,macro_f1,latency (s),cost ($/1k images)
1,qwen3-vl-8b_4bit_colab,open-source,0.855,0.863,0.798,17.718,0

,model_name,ecom_fg_acc,ecom_fg_micro_f1,ecom_fg_macro_f1,ecom_bg_acc,ecom_bg_micro_f1,ecom_bg_macro_f1,ecom_rel_acc,ecom_rel_micro_f1,ecom_rel_macro_f1,...,ecom_acc,ecom_micro_f1,ecom_macro_f1,news_acc,news_micro_f1,news_macro_f1,acc,micro_f1,macro_f1,latency (s)
1,qwen3-vl-8b_4bit_colab,0.974,0.974,0.941,0.842,0.842,0.879,1.0,1.0,1.0,...,0.939,0.939,0.916,0.644,0.667,0.603,0.855,0.863,0.798,17.718

## OpenRouter: Qwen3.8-27B

In [4]:
run("qwen3.8-27b_openrouter")
show("qwen3.8-27b_openrouter")

qwen3.8-27b_openrouter ecommerce:   3%|▎         | 1/38 [00:02<01:35,  2.57s/it]

ecommerce A_black_coffee_mug_on_an_office_desk_with_a_blurred_laptop_in_the_background.jpg {'relation': 'object_with_background', 'foreground': 'coffee_mug', 'background': 'woman'} 2.57s

qwen3.8-27b_openrouter ecommerce:   5%|▌         | 2/38 [00:05<01:33,  2.59s/it]

ecommerce a_camera_is_attached_to_a_tripod_with_a_mountain_in_the_background.jpg {'relation': 'object_with_background', 'foreground': 'camera', 'background': 'mountain'} 2.60s

qwen3.8-27b_openrouter ecommerce:   8%|▊         | 3/38 [00:08<01:43,  2.97s/it]

ecommerce a_camera_on_a_tripod_with_a_mountain_in_the_background.jpg {'relation': 'object_with_background', 'foreground': 'camera', 'background': 'mountain'} 3.42s

qwen3.8-27b_openrouter ecommerce:  11%|█         | 4/38 [00:09<01:18,  2.31s/it]

ecommerce A_close_up_shot_of_a_fountain_pen_with_an_ink_bottle_highlighted_by_warm_bokeh_lights_in_the_background.jpg {'relation': 'object_with_background', 'foreground': 'pen', 'background': 'blurred_lights'} 1.30s

qwen3.8-27b_openrouter ecommerce:  13%|█▎        | 5/38 [00:18<02:26,  4.44s/it]

ecommerce A_hand_holds_a_mushroom_themed_cup_indoors_focusing_on_coziness_with_a_blurred_screen_in_the_background.jpg {'relation': 'object_with_background', 'foreground': 'coffee_mug', 'background': 'blurred_laptop'} 8.22s

qwen3.8-27b_openrouter ecommerce:  16%|█▌        | 6/38 [00:20<01:55,  3.60s/it]

ecommerce A_hiking_backpack_resting_on_rocky_terrain_with_Tatra_Mountains_in_the_background.jpg {'relation': 'object_with_background', 'foreground': 'backpack', 'background': 'mountain'} 1.96s

qwen3.8-27b_openrouter ecommerce:  18%|█▊        | 7/38 [00:21<01:34,  3.04s/it]

ecommerce A_kettle_on_the_stove_with_a_teenage_boy_reading_a_book_in_the_background.jpg {'relation': 'object_with_background', 'foreground': 'kettle', 'background': 'man'} 1.87s

qwen3.8-27b_openrouter ecommerce:  21%|██        | 8/38 [00:23<01:19,  2.66s/it]

ecommerce A_Mobile_phone_charging_on_a_marble_table_with_a_pen_wallet_and_note_book_in_the_background.jpg {'relation': 'object_with_background', 'foreground': 'phone', 'background': 'blurred_lights'} 1.84s

qwen3.8-27b_openrouter ecommerce:  24%|██▎       | 9/38 [00:27<01:30,  3.11s/it]

ecommerce A_person_holding_up_a_pair_of_sunglasses_with_the_ocean_in_the_background.jpg {'relation': 'object_with_background', 'foreground': 'sunglasses', 'background': 'ocean'} 4.11s

qwen3.8-27b_openrouter ecommerce:  26%|██▋       | 10/38 [00:33<01:45,  3.78s/it]

ecommerce A_red_mug_on_a_coaster_with_a_blurred_person_in_the_background_indoors.jpg {'relation': 'object_with_background', 'foreground': 'coffee_mug', 'background': 'woman'} 5.27s

qwen3.8-27b_openrouter ecommerce:  29%|██▉       | 11/38 [00:35<01:33,  3.48s/it]

ecommerce A_smartphone_capturing_a_scenic_view_of_a_pebble_beach_with_blurred_hills_in_the_background.jpg {'relation': 'object_with_background', 'foreground': 'phone', 'background': 'mountain'} 2.80s

qwen3.8-27b_openrouter ecommerce:  32%|███▏      | 12/38 [00:41<01:46,  4.10s/it]

ecommerce A_striped_mug_in_focus_with_a_warm_artistic_bokeh_effect_in_the_background.jpg {'relation': 'object_with_background', 'foreground': 'coffee_mug', 'background': 'blurred_lights'} 5.53s

qwen3.8-27b_openrouter ecommerce:  34%|███▍      | 13/38 [00:43<01:27,  3.52s/it]

ecommerce A_vintage_camera_on_a_table_with_a_blurred_woman_in_the_background_holding_her_head.jpg {'relation': 'object_with_background', 'foreground': 'camera', 'background': 'woman'} 2.17s

qwen3.8-27b_openrouter ecommerce:  37%|███▋      | 14/38 [00:45<01:11,  2.99s/it]

ecommerce Artistic_shot_of_a_vintage_camera_with_blurred_digital_images_in_the_background.jpg {'relation': 'object_with_background', 'foreground': 'camera', 'background': 'blurred_laptop'} 1.76s

qwen3.8-27b_openrouter ecommerce:  39%|███▉      | 15/38 [00:50<01:21,  3.52s/it]

ecommerce Bright_yellow_mug_placed_on_concrete_with_blurred_urban_architecture_in_the_background.jpg {'relation': 'object_with_background', 'foreground': 'cup', 'background': 'urban_architecture'} 4.76s

qwen3.8-27b_openrouter ecommerce:  42%|████▏     | 16/38 [00:54<01:25,  3.88s/it]

ecommerce Camera_on_log_with_snowy_mountains_in_background.jpg {'relation': 'object_with_background', 'foreground': 'camera', 'background': 'mountain'} 4.72s

qwen3.8-27b_openrouter ecommerce:  45%|████▍     | 17/38 [00:57<01:15,  3.60s/it]

ecommerce Camera_on_tripod_capturing_a_cityscape_at_night_with_blurred_lights_in_the_background.jpg {'relation': 'object_with_background', 'foreground': 'camera', 'background': 'blurred_lights'} 2.95s

qwen3.8-27b_openrouter ecommerce:  47%|████▋     | 18/38 [00:58<00:55,  2.79s/it]

ecommerce Close_up_of_a_bar_of_green_soap_with_a_blank_white_label_resting_on_a_gray_surface_with_a_white_towel_in_the_background.jpg {'relation': 'object_with_background', 'foreground': 'soap', 'background': 'towel'} 0.89s

qwen3.8-27b_openrouter ecommerce:  50%|█████     | 19/38 [01:01<00:50,  2.66s/it]

ecommerce Close_up_of_a_decorative_Santa_mug_with_a_Christmas_tree_bokeh_in_the_background.jpg {'relation': 'object_with_background', 'foreground': 'coffee_mug', 'background': 'blurred_lights'} 2.36s

qwen3.8-27b_openrouter ecommerce:  53%|█████▎    | 20/38 [01:02<00:42,  2.36s/it]

ecommerce Close_up_of_a_DSLR_camera_on_a_desk_in_a_modern_office_setting_with_people_in_the_background.jpg {'relation': 'object_with_background', 'foreground': 'camera', 'background': 'people'} 1.66s

qwen3.8-27b_openrouter ecommerce:  55%|█████▌    | 21/38 [01:03<00:33,  1.97s/it]

ecommerce Close_up_of_a_professional_DSLR_camera_with_people_blurred_in_the_background.jpg {'relation': 'object_with_background', 'foreground': 'camera', 'background': 'people'} 1.05s

qwen3.8-27b_openrouter ecommerce:  58%|█████▊    | 22/38 [01:06<00:34,  2.16s/it]

ecommerce Close_up_of_a_vintage_camera_on_a_café_table_with_a_dessert_in_the_background.jpg {'relation': 'object_with_background', 'foreground': 'camera', 'background': 'dessert'} 2.60s

qwen3.8-27b_openrouter ecommerce:  61%|██████    | 23/38 [01:07<00:26,  1.76s/it]

ecommerce Close_up_of_alarm_clock_with_man_sleeping_in_the_background_Cape_Town_South_Africa.jpg {'relation': 'object_with_background', 'foreground': 'alarm_clock', 'background': 'man'} 0.82s

qwen3.8-27b_openrouter ecommerce:  63%|██████▎   | 24/38 [01:08<00:20,  1.47s/it]

ecommerce Close_up_of_water_bottle_in_locker_room_with_an_athlete_in_the_background.jpg {'relation': 'object_with_background', 'foreground': 'water_bottle', 'background': 'man'} 0.81s

qwen3.8-27b_openrouter ecommerce:  66%|██████▌   | 25/38 [01:09<00:17,  1.38s/it]

ecommerce Elegant_black_perfume_bottle_placed_on_a_textured_surface_with_vibrant_flowers_in_the_background_during_daylight.jpg {'relation': 'object_with_background', 'foreground': 'perfume_bottle', 'background': 'flowers'} 1.16s

qwen3.8-27b_openrouter ecommerce:  68%|██████▊   | 26/38 [01:10<00:14,  1.22s/it]

ecommerce Flower_vase_on_window_sill_with_father_and_son_in_background.jpg {'relation': 'object_with_background', 'foreground': 'flower_vase', 'background': 'man'} 0.83s

qwen3.8-27b_openrouter ecommerce:  71%|███████   | 27/38 [01:11<00:14,  1.36s/it]

ecommerce Golden_sunglasses_rest_on_a_table_by_the_beach_with_a_serene_sunset_and_palm_trees_in_the_background.jpg {'relation': 'object_with_background', 'foreground': 'sunglasses', 'background': 'ocean'} 1.68s

qwen3.8-27b_openrouter ecommerce:  74%|███████▎  | 28/38 [01:12<00:12,  1.21s/it]

ecommerce Hand_holding_a_coffee_cup_at_night_with_blurred_city_lights_in_the_background.jpg {'relation': 'object_with_background', 'foreground': 'coffee_mug', 'background': 'blurred_lights'} 0.86s

qwen3.8-27b_openrouter ecommerce:  76%|███████▋  | 29/38 [01:13<00:10,  1.12s/it]

ecommerce Laptop_on_wooden_table_in_a_loft_flat_with_man_at_the_window_in_background.jpg {'relation': 'object_with_background', 'foreground': 'laptop', 'background': 'man'} 0.91s

qwen3.8-27b_openrouter ecommerce:  79%|███████▉  | 30/38 [01:14<00:08,  1.04s/it]

ecommerce Notebook_and_coffee_cup_in_modern_informal_office_with_man_and_woman_in_background.jpg {'relation': 'object_with_background', 'foreground': 'coffee_mug', 'background': 'people'} 0.87s

qwen3.8-27b_openrouter ecommerce:  82%|████████▏ | 31/38 [01:15<00:06,  1.02it/s]

ecommerce Open_book_with_bookshelf_in_the_background.jpg {'relation': 'object_with_background', 'foreground': 'book', 'background': 'bookshelf'} 0.83s

qwen3.8-27b_openrouter ecommerce:  84%|████████▍ | 32/38 [01:16<00:05,  1.04it/s]

ecommerce Red_lentils_in_glass_jar_with_cooking_oil_bottle_and_woman_in_background_at_store.jpg {'relation': 'object_with_background', 'foreground': 'jar', 'background': 'woman'} 0.90s

qwen3.8-27b_openrouter ecommerce:  87%|████████▋ | 33/38 [01:17<00:06,  1.20s/it]

ecommerce Red_mug_with_bokeh_Christmas_lights_in_the_background_evoking_holiday_warmth_and_coziness.jpg {'relation': 'object_with_background', 'foreground': 'coffee_mug', 'background': 'blurred_lights'} 1.77s

qwen3.8-27b_openrouter ecommerce:  89%|████████▉ | 34/38 [01:18<00:04,  1.11s/it]

ecommerce Shaker_bottle_with_woman_working_out_in_the_background.jpg {'relation': 'object_with_background', 'foreground': 'water_bottle', 'background': 'woman'} 0.89s

qwen3.8-27b_openrouter ecommerce:  92%|█████████▏| 35/38 [01:19<00:03,  1.10s/it]

ecommerce Stylish_golden_glasses_with_colorful_bokeh_of_Dhaka_nightlife_in_the_background.jpg {'relation': 'object_with_background', 'foreground': 'sunglasses', 'background': 'blurred_lights'} 1.08s

qwen3.8-27b_openrouter ecommerce:  95%|█████████▍| 36/38 [01:21<00:02,  1.11s/it]

ecommerce Stylish_handbag_with_a_horse_in_the_background.jpg {'relation': 'object_with_background', 'foreground': 'handbag', 'background': 'horse'} 1.13s

qwen3.8-27b_openrouter ecommerce:  97%|█████████▋| 37/38 [01:22<00:01,  1.17s/it]

ecommerce Tortoiseshell_sunglasses_resting_on_a_sandy_beach_with_ocean_waves_in_the_background.jpg {'relation': 'object_with_background', 'foreground': 'sunglasses', 'background': 'ocean'} 1.32s

qwen3.8-27b_openrouter ecommerce: 100%|██████████| 38/38 [01:23<00:00,  2.19s/it]

ecommerce White_lamp_sits_in_foreground_adorned_with_silver_snowflake_ornament_and_unrecognizable_woman_in_yellow_in_background_adjusting_decorations_on_rwindow.jpg {'relation': 'object_with_background', 'foreground': 'lamp', 'background': 'woman'} 0.81s

qwen3.8-27b_openrouter news:   7%|▋         | 1/15 [00:03<00:54,  3.91s/it]

news Barack_Obama_at_Antalya.jpg {'relation': 'people_at_location', 'foreground': 'Barack_Obama', 'background': 'Antalya'} 3.90s

qwen3.8-27b_openrouter news:  13%|█▎        | 2/15 [00:07<00:47,  3.63s/it]

news Barack_Obama_at_United_Nations.jpg {'relation': 'people_at_location', 'foreground': 'Barack_Obama', 'background': 'United_Nations'} 3.43s

qwen3.8-27b_openrouter news:  20%|██        | 3/15 [00:11<00:45,  3.76s/it]

news Barack_Obama_at_White_House_Correspondents_Dinner.jpg {'relation': 'people_at_event', 'foreground': 'Barack_Obama', 'background': 'White_House_Correspondents_Dinner'} 3.92s

qwen3.8-27b_openrouter news:  27%|██▋       | 4/15 [00:15<00:43,  3.99s/it]

news Ben_Affleck_at_Argo_press_junket.jpg {'relation': 'people_at_event', 'foreground': 'Ben_Affleck', 'background': 'Argo_press_junket'} 4.33s

qwen3.8-27b_openrouter news:  33%|███▎      | 5/15 [00:21<00:46,  4.62s/it]

news Brad_Pitt_at_Venice_Film_Festival.jpg {'relation': 'people_at_event', 'foreground': 'Brad_Pitt', 'background': 'Venice_Film_Festival'} 5.73s

qwen3.8-27b_openrouter news:  40%|████      | 6/15 [00:24<00:36,  4.02s/it]

news Donald_Trump_at_NRCC.jpg {'relation': 'people_at_event', 'foreground': 'Donald_Trump', 'background': 'NRCC'} 2.87s

qwen3.8-27b_openrouter news:  47%|████▋     | 7/15 [00:28<00:32,  4.08s/it]

news Donald_Trump_at_Oval_Office2.jpg {'relation': 'people_at_location', 'foreground': 'Donald_Trump', 'background': 'White_House'} 4.20s

qwen3.8-27b_openrouter news:  53%|█████▎    | 8/15 [00:33<00:30,  4.33s/it]

news Donald_Trump_at_Oval_Office3.jpg {'relation': 'people_at_location', 'foreground': 'Donald_Trump', 'background': 'White_House'} 4.86s

qwen3.8-27b_openrouter news:  60%|██████    | 9/15 [00:36<00:23,  3.88s/it]

news Donald_Trump_at_Panama_City.jpg {'relation': 'people_at_event', 'foreground': 'Donald_Trump', 'background': 'White_House'} 2.91s

qwen3.8-27b_openrouter news:  67%|██████▋   | 10/15 [00:36<00:14,  2.93s/it]

news Donald_Trump_at_White_House9.jpg {'relation': 'people_at_location', 'foreground': 'Donald_Trump', 'background': 'White_House'} 0.78s

qwen3.8-27b_openrouter news:  73%|███████▎  | 11/15 [00:37<00:09,  2.27s/it]

news Joe_Biden_at_Buffalo.jpg {'relation': 'people_at_location', 'foreground': 'Joe_Biden', 'background': 'White_House'} 0.78s

qwen3.8-27b_openrouter news:  80%|████████  | 12/15 [00:38<00:05,  1.86s/it]

news Joe_Biden_at_Oval_Office.jpg {'relation': 'people_at_location', 'foreground': 'Joe_Biden', 'background': 'Oval_Office'} 0.91s

qwen3.8-27b_openrouter news:  87%|████████▋ | 13/15 [00:39<00:03,  1.55s/it]

news Joe_Biden_at_State_of_the_Union.jpg {'relation': 'people_at_event', 'foreground': 'Joe_Biden', 'background': 'State_of_the_Union'} 0.84s

qwen3.8-27b_openrouter news:  93%|█████████▎| 14/15 [00:40<00:01,  1.30s/it]

news Joe_Biden_at_White_House_Correspondents_Dinner.jpg {'relation': 'people_at_event', 'foreground': 'Joe_Biden', 'background': 'White_House_Correspondents_Dinner'} 0.73s

qwen3.8-27b_openrouter news: 100%|██████████| 15/15 [00:41<00:00,  2.74s/it]

news Mr_Bezos_at_Florida.jpg {'relation': 'people_at_event', 'foreground': 'Jeff_Bezos', 'background': 'Buffalo'} 0.84s
2.34s/image

,model_name,source,acc,micro_f1,macro_f1,latency (s),cost ($/1k images)
3,qwen3.8-27b_openrouter,commercial,0.918,0.918,0.861,2.342,0.16

,model_name,ecom_fg_acc,ecom_fg_micro_f1,ecom_fg_macro_f1,ecom_bg_acc,ecom_bg_micro_f1,ecom_bg_macro_f1,ecom_rel_acc,ecom_rel_micro_f1,ecom_rel_macro_f1,...,ecom_acc,ecom_micro_f1,ecom_macro_f1,news_acc,news_micro_f1,news_macro_f1,acc,micro_f1,macro_f1,latency (s)
3,qwen3.8-27b_openrouter,0.947,0.947,0.938,0.895,0.895,0.871,1.0,1.0,1.0,...,0.947,0.947,0.911,0.844,0.844,0.778,0.918,0.918,0.861,2.342

## OpenRouter: Qwen3-VL-30B-A3B

In [4]:
run("qwen3-vl-30b-a3b_openrouter")
show("qwen3-vl-30b-a3b_openrouter")

qwen3-vl-30b-a3b_openrouter ecommerce:   3%|▎         | 1/38 [00:03<01:51,  3.02s/it]

ecommerce A_black_coffee_mug_on_an_office_desk_with_a_blurred_laptop_in_the_background.jpg {'relation': 'object_with_background', 'foreground': 'coffee_mug', 'background': 'blurred_laptop'} 3.02s

qwen3-vl-30b-a3b_openrouter ecommerce:   5%|▌         | 2/38 [00:06<01:54,  3.17s/it]

ecommerce a_camera_is_attached_to_a_tripod_with_a_mountain_in_the_background.jpg {'relation': 'object_with_background', 'foreground': 'camera', 'background': 'mountain'} 3.28s

qwen3-vl-30b-a3b_openrouter ecommerce:   8%|▊         | 3/38 [00:08<01:37,  2.77s/it]

ecommerce a_camera_on_a_tripod_with_a_mountain_in_the_background.jpg {'relation': 'object_with_background', 'foreground': 'camera', 'background': 'mountain'} 2.29s

qwen3-vl-30b-a3b_openrouter ecommerce:  11%|█         | 4/38 [00:12<01:54,  3.36s/it]

ecommerce A_close_up_shot_of_a_fountain_pen_with_an_ink_bottle_highlighted_by_warm_bokeh_lights_in_the_background.jpg {'relation': 'object_with_background', 'foreground': 'pen', 'background': 'blurred_lights'} 4.25s

qwen3-vl-30b-a3b_openrouter ecommerce:  13%|█▎        | 5/38 [00:15<01:42,  3.10s/it]

ecommerce A_hand_holds_a_mushroom_themed_cup_indoors_focusing_on_coziness_with_a_blurred_screen_in_the_background.jpg {'relation': 'object_with_background', 'foreground': 'cup', 'background': 'blurred_laptop'} 2.65s

qwen3-vl-30b-a3b_openrouter ecommerce:  16%|█▌        | 6/38 [00:21<02:11,  4.11s/it]

ecommerce A_hiking_backpack_resting_on_rocky_terrain_with_Tatra_Mountains_in_the_background.jpg {'relation': 'object_with_background', 'foreground': 'backpack', 'background': 'mountain'} 6.06s

qwen3-vl-30b-a3b_openrouter ecommerce:  18%|█▊        | 7/38 [00:24<01:56,  3.77s/it]

ecommerce A_kettle_on_the_stove_with_a_teenage_boy_reading_a_book_in_the_background.jpg {'relation': 'object_with_background', 'foreground': 'kettle', 'background': 'woman'} 3.07s

qwen3-vl-30b-a3b_openrouter ecommerce:  21%|██        | 8/38 [00:26<01:33,  3.13s/it]

ecommerce A_Mobile_phone_charging_on_a_marble_table_with_a_pen_wallet_and_note_book_in_the_background.jpg {'relation': 'object_with_background', 'foreground': 'phone', 'background': 'blurred_laptop'} 1.75s

qwen3-vl-30b-a3b_openrouter ecommerce:  24%|██▎       | 9/38 [00:35<02:28,  5.12s/it]

ecommerce A_person_holding_up_a_pair_of_sunglasses_with_the_ocean_in_the_background.jpg {'relation': 'object_with_background', 'foreground': 'sunglasses', 'background': 'ocean'} 9.51s

qwen3-vl-30b-a3b_openrouter ecommerce:  26%|██▋       | 10/38 [00:41<02:29,  5.34s/it]

ecommerce A_red_mug_on_a_coaster_with_a_blurred_person_in_the_background_indoors.jpg {'relation': 'object_with_background', 'foreground': 'coffee_mug', 'background': 'woman'} 5.84s

qwen3-vl-30b-a3b_openrouter ecommerce:  29%|██▉       | 11/38 [00:47<02:26,  5.44s/it]

ecommerce A_smartphone_capturing_a_scenic_view_of_a_pebble_beach_with_blurred_hills_in_the_background.jpg {'relation': 'object_with_background', 'foreground': 'phone', 'background': 'mountain'} 5.67s

qwen3-vl-30b-a3b_openrouter ecommerce:  32%|███▏      | 12/38 [00:52<02:19,  5.35s/it]

ecommerce A_striped_mug_in_focus_with_a_warm_artistic_bokeh_effect_in_the_background.jpg {'relation': 'object_with_background', 'foreground': 'coffee_mug', 'background': 'blurred_lights'} 5.14s

qwen3-vl-30b-a3b_openrouter ecommerce:  34%|███▍      | 13/38 [00:58<02:19,  5.59s/it]

ecommerce A_vintage_camera_on_a_table_with_a_blurred_woman_in_the_background_holding_her_head.jpg {'relation': 'object_with_background', 'foreground': 'camera', 'background': 'woman'} 6.14s

qwen3-vl-30b-a3b_openrouter ecommerce:  37%|███▋      | 14/38 [01:05<02:24,  6.02s/it]

ecommerce Artistic_shot_of_a_vintage_camera_with_blurred_digital_images_in_the_background.jpg {'relation': 'object_with_background', 'foreground': 'camera', 'background': 'blurred_laptop'} 7.00s

qwen3-vl-30b-a3b_openrouter ecommerce:  39%|███▉      | 15/38 [01:08<01:53,  4.92s/it]

ecommerce Bright_yellow_mug_placed_on_concrete_with_blurred_urban_architecture_in_the_background.jpg {'relation': 'object_with_background', 'foreground': 'cup', 'background': 'urban_architecture'} 2.38s

qwen3-vl-30b-a3b_openrouter ecommerce:  42%|████▏     | 16/38 [01:13<01:49,  4.98s/it]

ecommerce Camera_on_log_with_snowy_mountains_in_background.jpg {'relation': 'object_with_background', 'foreground': 'camera', 'background': 'mountain'} 5.10s

qwen3-vl-30b-a3b_openrouter ecommerce:  45%|████▍     | 17/38 [01:19<01:53,  5.39s/it]

ecommerce Camera_on_tripod_capturing_a_cityscape_at_night_with_blurred_lights_in_the_background.jpg {'relation': 'object_with_background', 'foreground': 'camera', 'background': 'blurred_lights'} 6.36s

qwen3-vl-30b-a3b_openrouter ecommerce:  47%|████▋     | 18/38 [01:22<01:32,  4.63s/it]

ecommerce Close_up_of_a_bar_of_green_soap_with_a_blank_white_label_resting_on_a_gray_surface_with_a_white_towel_in_the_background.jpg {'relation': 'object_with_background', 'foreground': 'soap', 'background': 'towel'} 2.84s

qwen3-vl-30b-a3b_openrouter ecommerce:  50%|█████     | 19/38 [01:26<01:22,  4.36s/it]

ecommerce Close_up_of_a_decorative_Santa_mug_with_a_Christmas_tree_bokeh_in_the_background.jpg {'relation': 'object_with_background', 'foreground': 'coffee_mug', 'background': 'blurred_lights'} 3.73s

qwen3-vl-30b-a3b_openrouter ecommerce:  53%|█████▎    | 20/38 [01:31<01:22,  4.59s/it]

ecommerce Close_up_of_a_DSLR_camera_on_a_desk_in_a_modern_office_setting_with_people_in_the_background.jpg {'relation': 'object_with_background', 'foreground': 'camera', 'background': 'people'} 5.12s

qwen3-vl-30b-a3b_openrouter ecommerce:  55%|█████▌    | 21/38 [01:35<01:14,  4.38s/it]

ecommerce Close_up_of_a_professional_DSLR_camera_with_people_blurred_in_the_background.jpg {'relation': 'object_with_background', 'foreground': 'camera', 'background': 'people'} 3.89s

qwen3-vl-30b-a3b_openrouter ecommerce:  58%|█████▊    | 22/38 [01:41<01:19,  4.99s/it]

ecommerce Close_up_of_a_vintage_camera_on_a_café_table_with_a_dessert_in_the_background.jpg {'relation': 'object_with_background', 'foreground': 'camera', 'background': 'dessert'} 6.40s

qwen3-vl-30b-a3b_openrouter ecommerce:  61%|██████    | 23/38 [01:44<01:06,  4.41s/it]

ecommerce Close_up_of_alarm_clock_with_man_sleeping_in_the_background_Cape_Town_South_Africa.jpg {'relation': 'object_with_background', 'foreground': 'alarm_clock', 'background': 'man'} 3.08s

qwen3-vl-30b-a3b_openrouter ecommerce:  63%|██████▎   | 24/38 [01:48<00:59,  4.23s/it]

ecommerce Close_up_of_water_bottle_in_locker_room_with_an_athlete_in_the_background.jpg {'relation': 'object_with_background', 'foreground': 'water_bottle', 'background': 'man'} 3.81s

qwen3-vl-30b-a3b_openrouter ecommerce:  66%|██████▌   | 25/38 [01:52<00:52,  4.06s/it]

ecommerce Elegant_black_perfume_bottle_placed_on_a_textured_surface_with_vibrant_flowers_in_the_background_during_daylight.jpg {'relation': 'object_with_background', 'foreground': 'perfume_bottle', 'background': 'flowers'} 3.66s

qwen3-vl-30b-a3b_openrouter ecommerce:  68%|██████▊   | 26/38 [01:54<00:43,  3.64s/it]

ecommerce Flower_vase_on_window_sill_with_father_and_son_in_background.jpg {'relation': 'object_with_background', 'foreground': 'flower_vase', 'background': 'people'} 2.66s

qwen3-vl-30b-a3b_openrouter ecommerce:  71%|███████   | 27/38 [01:59<00:45,  4.12s/it]

ecommerce Golden_sunglasses_rest_on_a_table_by_the_beach_with_a_serene_sunset_and_palm_trees_in_the_background.jpg {'relation': 'object_with_background', 'foreground': 'sunglasses', 'background': 'ocean'} 5.25s

qwen3-vl-30b-a3b_openrouter ecommerce:  74%|███████▎  | 28/38 [02:05<00:43,  4.39s/it]

ecommerce Hand_holding_a_coffee_cup_at_night_with_blurred_city_lights_in_the_background.jpg {'relation': 'object_with_background', 'foreground': 'coffee_mug', 'background': 'blurred_lights'} 5.02s

qwen3-vl-30b-a3b_openrouter ecommerce:  76%|███████▋  | 29/38 [02:11<00:45,  5.01s/it]

ecommerce Laptop_on_wooden_table_in_a_loft_flat_with_man_at_the_window_in_background.jpg {'relation': 'object_with_background', 'foreground': 'laptop', 'background': 'man'} 6.46s

qwen3-vl-30b-a3b_openrouter ecommerce:  79%|███████▉  | 30/38 [02:13<00:32,  4.08s/it]

ecommerce Notebook_and_coffee_cup_in_modern_informal_office_with_man_and_woman_in_background.jpg {'relation': 'object_with_background', 'foreground': 'coffee_mug', 'background': 'people'} 1.91s

qwen3-vl-30b-a3b_openrouter ecommerce:  82%|████████▏ | 31/38 [02:17<00:28,  4.10s/it]

ecommerce Open_book_with_bookshelf_in_the_background.jpg {'relation': 'object_with_background', 'foreground': 'book', 'background': 'bookshelf'} 4.15s

qwen3-vl-30b-a3b_openrouter ecommerce:  84%|████████▍ | 32/38 [02:21<00:24,  4.10s/it]

ecommerce Red_lentils_in_glass_jar_with_cooking_oil_bottle_and_woman_in_background_at_store.jpg {'relation': 'object_with_background', 'foreground': 'jar', 'background': 'woman'} 4.08s

qwen3-vl-30b-a3b_openrouter ecommerce:  87%|████████▋ | 33/38 [02:26<00:21,  4.39s/it]

ecommerce Red_mug_with_bokeh_Christmas_lights_in_the_background_evoking_holiday_warmth_and_coziness.jpg {'relation': 'object_with_background', 'foreground': 'coffee_mug', 'background': 'blurred_lights'} 5.07s

qwen3-vl-30b-a3b_openrouter ecommerce:  89%|████████▉ | 34/38 [02:29<00:15,  3.80s/it]

ecommerce Shaker_bottle_with_woman_working_out_in_the_background.jpg {'relation': 'object_with_background', 'foreground': 'water_bottle', 'background': 'blurred_lights'} 2.40s

qwen3-vl-30b-a3b_openrouter ecommerce:  92%|█████████▏| 35/38 [02:36<00:14,  4.94s/it]

ecommerce Stylish_golden_glasses_with_colorful_bokeh_of_Dhaka_nightlife_in_the_background.jpg {'relation': 'object_with_background', 'foreground': 'sunglasses', 'background': 'blurred_lights'} 7.61s

qwen3-vl-30b-a3b_openrouter ecommerce:  95%|█████████▍| 36/38 [02:40<00:09,  4.51s/it]

ecommerce Stylish_handbag_with_a_horse_in_the_background.jpg {'relation': 'object_with_background', 'foreground': 'handbag', 'background': 'horse'} 3.50s

qwen3-vl-30b-a3b_openrouter ecommerce:  97%|█████████▋| 37/38 [02:46<00:05,  5.12s/it]

ecommerce Tortoiseshell_sunglasses_resting_on_a_sandy_beach_with_ocean_waves_in_the_background.jpg {'relation': 'object_with_background', 'foreground': 'sunglasses', 'background': 'ocean'} 6.55s

qwen3-vl-30b-a3b_openrouter ecommerce: 100%|██████████| 38/38 [02:50<00:00,  4.50s/it]

ecommerce White_lamp_sits_in_foreground_adorned_with_silver_snowflake_ornament_and_unrecognizable_woman_in_yellow_in_background_adjusting_decorations_on_rwindow.jpg {'relation': 'object_with_background', 'foreground': 'lamp', 'background': 'blurred_lights'} 4.19s

qwen3-vl-30b-a3b_openrouter news:   7%|▋         | 1/15 [00:01<00:25,  1.85s/it]

news Barack_Obama_at_Antalya.jpg {'relation': 'people_at_event', 'foreground': 'Barack_Obama', 'background': 'Antalya'} 1.85s

qwen3-vl-30b-a3b_openrouter news:  13%|█▎        | 2/15 [00:03<00:24,  1.91s/it]

news Barack_Obama_at_United_Nations.jpg {'relation': 'people_at_event', 'foreground': 'Barack_Obama', 'background': 'United_Nations'} 1.95s

qwen3-vl-30b-a3b_openrouter news:  20%|██        | 3/15 [00:06<00:24,  2.06s/it]

news Barack_Obama_at_White_House_Correspondents_Dinner.jpg {'relation': 'people_at_event', 'foreground': 'Barack_Obama', 'background': 'White_House_Correspondents_Dinner'} 2.24s

qwen3-vl-30b-a3b_openrouter news:  27%|██▋       | 4/15 [00:07<00:20,  1.89s/it]

news Ben_Affleck_at_Argo_press_junket.jpg {'relation': 'people_at_event', 'foreground': 'Ben_Affleck', 'background': 'Argo_press_junket'} 1.63s

qwen3-vl-30b-a3b_openrouter news:  33%|███▎      | 5/15 [00:11<00:24,  2.43s/it]

news Brad_Pitt_at_Venice_Film_Festival.jpg {'relation': 'people_at_event', 'foreground': 'Brad_Pitt', 'background': 'Venice_Film_Festival'} 3.39s

qwen3-vl-30b-a3b_openrouter news:  40%|████      | 6/15 [00:13<00:20,  2.27s/it]

news Donald_Trump_at_NRCC.jpg {'relation': 'people_at_event', 'foreground': 'Donald_Trump', 'background': 'NRCC'} 1.94s

qwen3-vl-30b-a3b_openrouter news:  47%|████▋     | 7/15 [00:15<00:18,  2.33s/it]

news Donald_Trump_at_Oval_Office2.jpg {'relation': 'people_at_location', 'foreground': 'Donald_Trump', 'background': 'White_House'} 2.45s

qwen3-vl-30b-a3b_openrouter news:  53%|█████▎    | 8/15 [00:17<00:16,  2.37s/it]

news Donald_Trump_at_Oval_Office3.jpg {'relation': 'people_at_location', 'foreground': 'Donald_Trump', 'background': 'White_House'} 2.47s

qwen3-vl-30b-a3b_openrouter news:  60%|██████    | 9/15 [00:20<00:13,  2.32s/it]

news Donald_Trump_at_Panama_City.jpg {'relation': 'people_at_event', 'foreground': 'Donald_Trump', 'background': 'State_of_the_Union'} 2.21s

qwen3-vl-30b-a3b_openrouter news:  67%|██████▋   | 10/15 [00:23<00:12,  2.53s/it]

news Donald_Trump_at_White_House9.jpg {'relation': 'people_at_location', 'foreground': 'Donald_Trump', 'background': 'Oval_Office'} 2.97s

qwen3-vl-30b-a3b_openrouter news:  73%|███████▎  | 11/15 [00:28<00:13,  3.29s/it]

news Joe_Biden_at_Buffalo.jpg {'relation': 'people_at_event', 'foreground': 'Joe_Biden', 'background': 'White_House_Correspondents_Dinner'} 5.02s

qwen3-vl-30b-a3b_openrouter news:  80%|████████  | 12/15 [00:35<00:13,  4.44s/it]

news Joe_Biden_at_Oval_Office.jpg {'relation': 'people_at_location', 'foreground': 'Joe_Biden', 'background': 'Oval_Office'} 7.08s

qwen3-vl-30b-a3b_openrouter news:  87%|████████▋ | 13/15 [00:41<00:09,  4.87s/it]

news Joe_Biden_at_State_of_the_Union.jpg {'relation': 'people_at_event', 'foreground': 'Joe_Biden', 'background': 'State_of_the_Union'} 5.86s

qwen3-vl-30b-a3b_openrouter news:  93%|█████████▎| 14/15 [00:49<00:05,  5.83s/it]

news Joe_Biden_at_White_House_Correspondents_Dinner.jpg {'relation': 'people_at_event', 'foreground': 'Joe_Biden', 'background': 'White_House_Correspondents_Dinner'} 8.04s

qwen3-vl-30b-a3b_openrouter news: 100%|██████████| 15/15 [00:54<00:00,  3.63s/it]

news Mr_Bezos_at_Florida.jpg {'relation': 'people_at_event', 'foreground': 'Jeff_Bezos', 'background': 'Argo_press_junket'} 5.32s
4.25s/image

,model_name,source,acc,micro_f1,macro_f1,latency (s),cost ($/1k images)
4,qwen3-vl-30b-a3b_openrouter,commercial,0.899,0.899,0.843,4.251,0.279

,model_name,ecom_fg_acc,ecom_fg_micro_f1,ecom_fg_macro_f1,ecom_bg_acc,ecom_bg_micro_f1,ecom_bg_macro_f1,ecom_rel_acc,ecom_rel_micro_f1,ecom_rel_macro_f1,...,ecom_acc,ecom_micro_f1,ecom_macro_f1,news_acc,news_micro_f1,news_macro_f1,acc,micro_f1,macro_f1,latency (s)
4,qwen3-vl-30b-a3b_openrouter,0.974,0.974,0.978,0.895,0.895,0.874,1.0,1.0,1.0,...,0.956,0.956,0.934,0.756,0.756,0.693,0.899,0.899,0.843,4.251

## Gemini: 3.1 Flash-Lite

In [4]:
run("gemini-3.1-flash-lite_google")
show("gemini-3.1-flash-lite_google")

gemini-3.1-flash-lite_google ecommerce:   0%|          | 0/38 [00:02<?, ?it/s]

ecommerce A_black_coffee_mug_on_an_office_desk_with_a_blurred_laptop_in_the_background.jpg {'relation': 'object_with_background', 'foreground': 'coffee_mug', 'background': 'blurred_laptop'} 2.09s

gemini-3.1-flash-lite_google ecommerce:   3%|▎         | 1/38 [00:13<04:59,  8.10s/it]

ecommerce a_camera_is_attached_to_a_tripod_with_a_mountain_in_the_background.jpg {'relation': 'object_with_background', 'foreground': 'camera', 'background': 'mountain'} 5.61s

gemini-3.1-flash-lite_google ecommerce:   5%|▌         | 2/38 [00:23<06:05, 10.16s/it]

ecommerce a_camera_on_a_tripod_with_a_mountain_in_the_background.jpg {'relation': 'object_with_background', 'foreground': 'camera', 'background': 'mountain'} 3.51s

gemini-3.1-flash-lite_google ecommerce:   8%|▊         | 3/38 [00:35<05:45,  9.87s/it]

ecommerce A_close_up_shot_of_a_fountain_pen_with_an_ink_bottle_highlighted_by_warm_bokeh_lights_in_the_background.jpg {'relation': 'object_with_background', 'foreground': 'pen', 'background': 'blurred_lights'} 6.29s

gemini-3.1-flash-lite_google ecommerce:  11%|█         | 4/38 [00:46<06:07, 10.82s/it]

ecommerce A_hand_holds_a_mushroom_themed_cup_indoors_focusing_on_coziness_with_a_blurred_screen_in_the_background.jpg {'relation': 'object_with_background', 'foreground': 'coffee_mug', 'background': 'blurred_laptop'} 4.66s

gemini-3.1-flash-lite_google ecommerce:  13%|█▎        | 5/38 [01:21<05:55, 10.76s/it]

ecommerce A_hiking_backpack_resting_on_rocky_terrain_with_Tatra_Mountains_in_the_background.jpg {'relation': 'object_with_background', 'foreground': 'backpack', 'background': 'mountain'} 29.77s

gemini-3.1-flash-lite_google ecommerce:  16%|█▌        | 6/38 [01:29<10:16, 19.27s/it]

ecommerce A_kettle_on_the_stove_with_a_teenage_boy_reading_a_book_in_the_background.jpg {'relation': 'object_with_background', 'foreground': 'kettle', 'background': 'man'} 1.98s

gemini-3.1-flash-lite_google ecommerce:  18%|█▊        | 7/38 [01:40<08:02, 15.58s/it]

ecommerce A_Mobile_phone_charging_on_a_marble_table_with_a_pen_wallet_and_note_book_in_the_background.jpg {'relation': 'object_with_background', 'foreground': 'phone', 'background': 'pen'} 4.54s

gemini-3.1-flash-lite_google ecommerce:  21%|██        | 8/38 [01:52<06:59, 13.97s/it]

ecommerce A_person_holding_up_a_pair_of_sunglasses_with_the_ocean_in_the_background.jpg {'relation': 'object_with_background', 'foreground': 'sunglasses', 'background': 'ocean'} 5.87s

gemini-3.1-flash-lite_google ecommerce:  24%|██▎       | 9/38 [02:00<06:26, 13.32s/it]

ecommerce A_red_mug_on_a_coaster_with_a_blurred_person_in_the_background_indoors.jpg {'relation': 'object_with_background', 'foreground': 'coffee_mug', 'background': 'woman'} 2.30s

gemini-3.1-flash-lite_google ecommerce:  26%|██▋       | 10/38 [02:08<05:29, 11.77s/it]

ecommerce A_smartphone_capturing_a_scenic_view_of_a_pebble_beach_with_blurred_hills_in_the_background.jpg {'relation': 'object_with_background', 'foreground': 'phone', 'background': 'mountain'} 2.22s

gemini-3.1-flash-lite_google ecommerce:  29%|██▉       | 11/38 [02:16<04:48, 10.68s/it]

ecommerce A_striped_mug_in_focus_with_a_warm_artistic_bokeh_effect_in_the_background.jpg {'relation': 'object_with_background', 'foreground': 'coffee_mug', 'background': 'blurred_lights'} 2.00s

gemini-3.1-flash-lite_google ecommerce:  32%|███▏      | 12/38 [02:25<04:16,  9.87s/it]

ecommerce A_vintage_camera_on_a_table_with_a_blurred_woman_in_the_background_holding_her_head.jpg {'relation': 'object_with_background', 'foreground': 'camera', 'background': 'woman'} 2.50s

gemini-3.1-flash-lite_google ecommerce:  34%|███▍      | 13/38 [02:34<03:56,  9.46s/it]

ecommerce Artistic_shot_of_a_vintage_camera_with_blurred_digital_images_in_the_background.jpg {'relation': 'object_with_background', 'foreground': 'camera', 'background': 'blurred_laptop'} 3.08s

gemini-3.1-flash-lite_google ecommerce:  37%|███▋      | 14/38 [02:42<03:44,  9.34s/it]

ecommerce Bright_yellow_mug_placed_on_concrete_with_blurred_urban_architecture_in_the_background.jpg {'relation': 'object_with_background', 'foreground': 'cup', 'background': 'urban_architecture'} 1.96s

gemini-3.1-flash-lite_google ecommerce:  39%|███▉      | 15/38 [02:50<03:25,  8.93s/it]

ecommerce Camera_on_log_with_snowy_mountains_in_background.jpg {'relation': 'object_with_background', 'foreground': 'camera', 'background': 'mountain'} 2.56s

gemini-3.1-flash-lite_google ecommerce:  42%|████▏     | 16/38 [02:59<03:13,  8.82s/it]

ecommerce Camera_on_tripod_capturing_a_cityscape_at_night_with_blurred_lights_in_the_background.jpg {'relation': 'object_with_background', 'foreground': 'camera', 'background': 'blurred_lights'} 2.32s

gemini-3.1-flash-lite_google ecommerce:  45%|████▍     | 17/38 [03:07<03:02,  8.67s/it]

ecommerce Close_up_of_a_bar_of_green_soap_with_a_blank_white_label_resting_on_a_gray_surface_with_a_white_towel_in_the_background.jpg {'relation': 'object_with_background', 'foreground': 'soap', 'background': 'towel'} 1.71s

gemini-3.1-flash-lite_google ecommerce:  47%|████▋     | 18/38 [03:15<02:47,  8.38s/it]

ecommerce Close_up_of_a_decorative_Santa_mug_with_a_Christmas_tree_bokeh_in_the_background.jpg {'relation': 'object_with_background', 'foreground': 'coffee_mug', 'background': 'blurred_lights'} 2.70s

gemini-3.1-flash-lite_google ecommerce:  50%|█████     | 19/38 [03:23<02:41,  8.48s/it]

ecommerce Close_up_of_a_DSLR_camera_on_a_desk_in_a_modern_office_setting_with_people_in_the_background.jpg {'relation': 'object_with_background', 'foreground': 'camera', 'background': 'people'} 2.19s

gemini-3.1-flash-lite_google ecommerce:  53%|█████▎    | 20/38 [03:31<02:31,  8.39s/it]

ecommerce Close_up_of_a_professional_DSLR_camera_with_people_blurred_in_the_background.jpg {'relation': 'object_with_background', 'foreground': 'camera', 'background': 'people'} 1.88s

gemini-3.1-flash-lite_google ecommerce:  55%|█████▌    | 21/38 [03:40<02:20,  8.24s/it]

ecommerce Close_up_of_a_vintage_camera_on_a_café_table_with_a_dessert_in_the_background.jpg {'relation': 'object_with_background', 'foreground': 'camera', 'background': 'dessert'} 2.80s

gemini-3.1-flash-lite_google ecommerce:  58%|█████▊    | 22/38 [03:48<02:14,  8.41s/it]

ecommerce Close_up_of_alarm_clock_with_man_sleeping_in_the_background_Cape_Town_South_Africa.jpg {'relation': 'object_with_background', 'foreground': 'alarm_clock', 'background': 'people'} 1.58s

gemini-3.1-flash-lite_google ecommerce:  61%|██████    | 23/38 [03:55<02:02,  8.16s/it]

ecommerce Close_up_of_water_bottle_in_locker_room_with_an_athlete_in_the_background.jpg {'relation': 'object_with_background', 'foreground': 'water_bottle', 'background': 'man'} 1.58s

gemini-3.1-flash-lite_google ecommerce:  63%|██████▎   | 24/38 [04:03<01:51,  7.99s/it]

ecommerce Elegant_black_perfume_bottle_placed_on_a_textured_surface_with_vibrant_flowers_in_the_background_during_daylight.jpg {'relation': 'object_with_background', 'foreground': 'perfume_bottle', 'background': 'flowers'} 1.86s

gemini-3.1-flash-lite_google ecommerce:  66%|██████▌   | 25/38 [04:11<01:43,  7.95s/it]

ecommerce Flower_vase_on_window_sill_with_father_and_son_in_background.jpg {'relation': 'object_with_background', 'foreground': 'flower_vase', 'background': 'people'} 1.90s

gemini-3.1-flash-lite_google ecommerce:  68%|██████▊   | 26/38 [04:19<01:35,  7.94s/it]

ecommerce Golden_sunglasses_rest_on_a_table_by_the_beach_with_a_serene_sunset_and_palm_trees_in_the_background.jpg {'relation': 'object_with_background', 'foreground': 'sunglasses', 'background': 'ocean'} 2.44s

gemini-3.1-flash-lite_google ecommerce:  71%|███████   | 27/38 [04:27<01:28,  8.09s/it]

ecommerce Hand_holding_a_coffee_cup_at_night_with_blurred_city_lights_in_the_background.jpg {'relation': 'object_with_background', 'foreground': 'coffee_mug', 'background': 'blurred_lights'} 1.80s

gemini-3.1-flash-lite_google ecommerce:  74%|███████▎  | 28/38 [04:35<01:20,  8.00s/it]

ecommerce Laptop_on_wooden_table_in_a_loft_flat_with_man_at_the_window_in_background.jpg {'relation': 'object_with_background', 'foreground': 'laptop', 'background': 'man'} 1.91s

gemini-3.1-flash-lite_google ecommerce:  76%|███████▋  | 29/38 [04:43<01:11,  7.98s/it]

ecommerce Notebook_and_coffee_cup_in_modern_informal_office_with_man_and_woman_in_background.jpg {'relation': 'object_with_background', 'foreground': 'coffee_mug', 'background': 'people'} 1.94s

gemini-3.1-flash-lite_google ecommerce:  79%|███████▉  | 30/38 [04:51<01:03,  7.97s/it]

ecommerce Open_book_with_bookshelf_in_the_background.jpg {'relation': 'object_with_background', 'foreground': 'book', 'background': 'bookshelf'} 1.86s

gemini-3.1-flash-lite_google ecommerce:  82%|████████▏ | 31/38 [04:59<00:55,  7.93s/it]

ecommerce Red_lentils_in_glass_jar_with_cooking_oil_bottle_and_woman_in_background_at_store.jpg {'relation': 'object_with_background', 'foreground': 'jar', 'background': 'woman'} 1.95s

gemini-3.1-flash-lite_google ecommerce:  84%|████████▍ | 32/38 [05:08<00:47,  7.94s/it]

ecommerce Red_mug_with_bokeh_Christmas_lights_in_the_background_evoking_holiday_warmth_and_coziness.jpg {'relation': 'object_with_background', 'foreground': 'coffee_mug', 'background': 'blurred_lights'} 3.01s

gemini-3.1-flash-lite_google ecommerce:  87%|████████▋ | 33/38 [05:16<00:41,  8.26s/it]

ecommerce Shaker_bottle_with_woman_working_out_in_the_background.jpg {'relation': 'object_with_background', 'foreground': 'water_bottle', 'background': 'people'} 2.16s

gemini-3.1-flash-lite_google ecommerce:  89%|████████▉ | 34/38 [05:25<00:32,  8.23s/it]

ecommerce Stylish_golden_glasses_with_colorful_bokeh_of_Dhaka_nightlife_in_the_background.jpg {'relation': 'object_with_background', 'foreground': 'sunglasses', 'background': 'blurred_lights'} 2.63s

gemini-3.1-flash-lite_google ecommerce:  92%|█████████▏| 35/38 [05:33<00:25,  8.35s/it]

ecommerce Stylish_handbag_with_a_horse_in_the_background.jpg {'relation': 'object_with_background', 'foreground': 'handbag', 'background': 'horse'} 1.94s

gemini-3.1-flash-lite_google ecommerce:  95%|█████████▍| 36/38 [05:41<00:16,  8.23s/it]

ecommerce Tortoiseshell_sunglasses_resting_on_a_sandy_beach_with_ocean_waves_in_the_background.jpg {'relation': 'object_with_background', 'foreground': 'sunglasses', 'background': 'ocean'} 2.23s

gemini-3.1-flash-lite_google ecommerce:  97%|█████████▋| 37/38 [05:49<00:08,  8.23s/it]

ecommerce White_lamp_sits_in_foreground_adorned_with_silver_snowflake_ornament_and_unrecognizable_woman_in_yellow_in_background_adjusting_decorations_on_rwindow.jpg {'relation': 'object_with_background', 'foreground': 'lamp', 'background': 'woman'} 1.90s

gemini-3.1-flash-lite_google ecommerce: 100%|██████████| 38/38 [05:55<00:00,  9.35s/it]
gemini-3.1-flash-lite_google news:   0%|          | 0/15 [00:03<?, ?it/s]

news Barack_Obama_at_Antalya.jpg {'relation': 'people_at_location', 'foreground': 'Barack_Obama', 'background': 'Antalya'} 3.54s

gemini-3.1-flash-lite_google news:   7%|▋         | 1/15 [00:11<02:13,  9.54s/it]

news Barack_Obama_at_United_Nations.jpg {'relation': 'people_at_location', 'foreground': 'Barack_Obama', 'background': 'United_Nations'} 2.15s

gemini-3.1-flash-lite_google news:  13%|█▎        | 2/15 [00:21<01:53,  8.72s/it]

news Barack_Obama_at_White_House_Correspondents_Dinner.jpg {'relation': 'people_at_event', 'foreground': 'Barack_Obama', 'background': 'White_House_Correspondents_Dinner'} 3.49s

gemini-3.1-flash-lite_google news:  20%|██        | 3/15 [00:29<01:48,  9.08s/it]

news Ben_Affleck_at_Argo_press_junket.jpg {'relation': 'people_at_event', 'foreground': 'Ben_Affleck', 'background': 'Argo_press_junket'} 2.59s

gemini-3.1-flash-lite_google news:  27%|██▋       | 4/15 [00:37<01:37,  8.88s/it]

news Brad_Pitt_at_Venice_Film_Festival.jpg {'relation': 'people_at_event', 'foreground': 'Brad_Pitt', 'background': 'Venice_Film_Festival'} 1.96s

gemini-3.1-flash-lite_google news:  33%|███▎      | 5/15 [00:46<01:25,  8.55s/it]

news Donald_Trump_at_NRCC.jpg {'relation': 'people_at_event', 'foreground': 'Donald_Trump', 'background': 'NRCC'} 2.39s

gemini-3.1-flash-lite_google news:  40%|████      | 6/15 [00:53<01:16,  8.50s/it]

news Donald_Trump_at_Oval_Office2.jpg {'relation': 'people_at_location', 'foreground': 'Donald_Trump', 'background': 'White_House'} 1.79s

gemini-3.1-flash-lite_google news:  47%|████▋     | 7/15 [01:01<01:06,  8.27s/it]

news Donald_Trump_at_Oval_Office3.jpg {'relation': 'people_at_location', 'foreground': 'Donald_Trump', 'background': 'White_House'} 2.06s

gemini-3.1-flash-lite_google news:  53%|█████▎    | 8/15 [01:10<00:57,  8.20s/it]

news Donald_Trump_at_Panama_City.jpg {'relation': 'people_at_location', 'foreground': 'Donald_Trump', 'background': 'Florida'} 2.09s

gemini-3.1-flash-lite_google news:  60%|██████    | 9/15 [01:18<00:49,  8.17s/it]

news Donald_Trump_at_White_House9.jpg {'relation': 'people_at_location', 'foreground': 'Donald_Trump', 'background': 'Oval_Office'} 2.17s

gemini-3.1-flash-lite_google news:  67%|██████▋   | 10/15 [01:27<00:40,  8.17s/it]

news Joe_Biden_at_Buffalo.jpg {'relation': 'people_at_location', 'foreground': 'Joe_Biden', 'background': 'White_House'} 3.45s

gemini-3.1-flash-lite_google news:  73%|███████▎  | 11/15 [01:35<00:34,  8.56s/it]

news Joe_Biden_at_Oval_Office.jpg {'relation': 'people_at_location', 'foreground': 'Joe_Biden', 'background': 'Oval_Office'} 2.27s

gemini-3.1-flash-lite_google news:  80%|████████  | 12/15 [01:44<00:25,  8.47s/it]

news Joe_Biden_at_State_of_the_Union.jpg {'relation': 'people_at_event', 'foreground': 'Joe_Biden', 'background': 'State_of_the_Union'} 2.24s

gemini-3.1-flash-lite_google news:  87%|████████▋ | 13/15 [01:52<00:16,  8.40s/it]

news Joe_Biden_at_White_House_Correspondents_Dinner.jpg {'relation': 'people_at_event', 'foreground': 'Joe_Biden', 'background': 'White_House_Correspondents_Dinner'} 1.96s

gemini-3.1-flash-lite_google news:  93%|█████████▎| 14/15 [02:00<00:08,  8.27s/it]

news Mr_Bezos_at_Florida.jpg {'relation': 'people_at_location', 'foreground': 'Jeff_Bezos', 'background': 'Florida'} 1.99s

gemini-3.1-flash-lite_google news: 100%|██████████| 15/15 [02:06<00:00,  8.41s/it]

3.08s/image

,model_name,source,acc,micro_f1,macro_f1,latency (s),cost ($/1k images)
5,gemini-3.1-flash-lite_google,commercial,0.937,0.937,0.891,3.083,0.485

,model_name,ecom_fg_acc,ecom_fg_micro_f1,ecom_fg_macro_f1,ecom_bg_acc,ecom_bg_micro_f1,ecom_bg_macro_f1,ecom_rel_acc,ecom_rel_micro_f1,ecom_rel_macro_f1,...,ecom_acc,ecom_micro_f1,ecom_macro_f1,news_acc,news_micro_f1,news_macro_f1,acc,micro_f1,macro_f1,latency (s)
5,gemini-3.1-flash-lite_google,0.947,0.947,0.938,0.921,0.921,0.95,1.0,1.0,1.0,...,0.956,0.956,0.945,0.889,0.889,0.803,0.937,0.937,0.891,3.083

## Results

In [5]:
display(pd.read_csv("results/overall_metrics.csv"))
pd.read_csv("results/metrics.csv")

,model_name,source,acc,micro_f1,macro_f1,latency (s),cost ($/1k images)
0,qwen3-vl-2b_4bit_local,open-source,0.811,0.830,0.768,1.164,0.000
1,qwen3-vl-4b_colab,open-source,0.855,0.863,0.774,3.477,0.000
2,qwen3-vl-8b_4bit_colab,open-source,0.855,0.863,0.798,17.718,0.000
3,qwen3.8-27b_openrouter,commercial,0.918,0.918,0.861,2.342,0.160
4,qwen3-vl-30b-a3b_openrouter,commercial,0.899,0.899,0.843,4.251,0.279
5,gemini-3.1-flash-lite_google,commercial,0.937,0.937,0.891,3.083,0.485

,model_name,ecom_fg_acc,ecom_fg_micro_f1,ecom_fg_macro_f1,ecom_bg_acc,ecom_bg_micro_f1,ecom_bg_macro_f1,ecom_rel_acc,ecom_rel_micro_f1,ecom_rel_macro_f1,...,ecom_acc,ecom_micro_f1,ecom_macro_f1,news_acc,news_micro_f1,news_macro_f1,acc,micro_f1,macro_f1,latency (s)
0,qwen3-vl-2b_4bit_local,0.974,0.974,0.941,0.737,0.778,0.741,0.974,0.987,0.987,...,0.895,0.915,0.858,0.600,0.614,0.621,0.811,0.830,0.768,1.164
1,qwen3-vl-4b_colab,0.974,0.974,0.941,0.789,0.789,0.796,1.000,1.000,1.000,...,0.921,0.921,0.881,0.689,0.713,0.598,0.855,0.863,0.774,3.477
2,qwen3-vl-8b_4bit_colab,0.974,0.974,0.941,0.842,0.842,0.879,1.000,1.000,1.000,...,0.939,0.939,0.916,0.644,0.667,0.603,0.855,0.863,0.798,17.718
3,qwen3.8-27b_openrouter,0.947,0.947,0.938,0.895,0.895,0.871,1.000,1.000,1.000,...,0.947,0.947,0.911,0.844,0.844,0.778,0.918,0.918,0.861,2.342
4,qwen3-vl-30b-a3b_openrouter,0.974,0.974,0.978,0.895,0.895,0.874,1.000,1.000,1.000,...,0.956,0.956,0.934,0.756,0.756,0.693,0.899,0.899,0.843,4.251
5,gemini-3.1-flash-lite_google,0.947,0.947,0.938,0.921,0.921,0.950,1.000,1.000,1.000,...,0.956,0.956,0.945,0.889,0.889,0.803,0.937,0.937,0.891,3.083