In [1]:
! nvidia-smi

Wed Oct 14 21:22:12 2026
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 580.82.07              Driver Version: 580.82.07      CUDA Version: 13.0     |
+-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   44C    P8             14W /   70W |       0MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+

+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI              PID   Type   Process name                        GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|  No running processes found                                                             |
+-----------------------------------------------------------------------------------------+

In [2]:
import io, os, sys, zipfile, urllib.request
from pathlib import Path

if "google.colab" in sys.modules:
    os.chdir("/content")
    sys.path.insert(0, "/content")

    need_src = not Path("src/utils/evaluate.py").is_file()
    need_data = not Path("data/ecommerce/gt_images.json").exists()
    need_req = not Path("requirements.txt").exists()
    if need_src or need_data or need_req:
        url = "https://codeload.github.com/ranjanrakesh47g/ObjectDetection/zip/refs/heads/main"
        with zipfile.ZipFile(io.BytesIO(urllib.request.urlopen(url).read())) as zipped:
            prefix = next(name for name in zipped.namelist() if name.endswith("data/ecommerce/gt_images.json")).split("data/")[0]
            names = []
            if need_req:
                names.append(prefix + "requirements.txt")
            if need_data:
                names += [name for name in zipped.namelist() if name.startswith(prefix + "data/") and not name.endswith("/")]
            if need_src:
                names += [name for name in zipped.namelist() if name.startswith(prefix + "src/") and not name.endswith("/")]
            for name in names:
                dest = Path(name[len(prefix):])
                dest.parent.mkdir(parents=True, exist_ok=True)
                dest.write_bytes(zipped.read(name))

    get_ipython().run_line_magic("pip", "install -q -r requirements.txt")
    if not Path("/tmp/colab_restarted").exists():
        Path("/tmp/colab_restarted").write_text("1")
        print("Restarting the runtime so torch and torchvision reload.")
        get_ipython().kernel.do_shutdown(restart=True)

Restarting the runtime so torch and torchvision reload.

In [3]:
import pandas as pd
from src.utils import run

def show(name):
    overall = pd.read_csv("results/overall_metrics.csv").query("model_name == @name")
    detail = pd.read_csv("results/metrics.csv").query("model_name == @name")
    display(overall)
    display(detail)

## Local GPU: Qwen3-VL-2B, 4-bit

In [4]:
run("qwen3-vl-2b_4bit_local")
show("qwen3-vl-2b_4bit_local")

/home/rakesh/Downloads/ShortTok/3.ObjectDetection/ObjectDetection/.venv/lib/python3.12/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
Loading weights: 100%|██████████| 625/625 [00:06<00:00, 91.36it/s]
qwen3-vl-2b_4bit_local ecommerce:   0%|          | 0/38 [00:00<?, ?it/s][transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
/home/rakesh/Downloads/ShortTok/3.ObjectDetection/ObjectDetection/.venv/lib/python3.12/site-packages/transformers/models/qwen2_vl/image_processing_qwen2_vl.py:129: FutureWarning: Passing `min_pixels` and `max_pixels` to a processor call is deprecated and will be removed in v5.23. Pass in `size={'longest_edge': xxx, 'shortest_edge': xxx} to override the target size.`
  warnings.warn(
qwen3-vl-2b_4bit_local ecommerce:   3%|▎         | 1/38 [00:02<01:48,  2.92s/it][transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`

ecommerce A_black_coffee_mug_on_an_office_desk_with_a_blurred_laptop_in_the_background.jpg {'foreground': 'coffee_mug', 'background': '', 'relation': 'object_with_background'} 2.92s

qwen3-vl-2b_4bit_local ecommerce:   5%|▌         | 2/38 [00:04<01:11,  1.99s/it][transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`

ecommerce a_camera_is_attached_to_a_tripod_with_a_mountain_in_the_background.jpg {'foreground': 'camera', 'background': 'urban_architecture', 'relation': 'object_with_background'} 1.33s

qwen3-vl-2b_4bit_local ecommerce:   8%|▊         | 3/38 [00:05<01:00,  1.73s/it][transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`

ecommerce a_camera_on_a_tripod_with_a_mountain_in_the_background.jpg {'foreground': 'camera', 'background': 'mountain', 'relation': 'object_with_background'} 1.41s

qwen3-vl-2b_4bit_local ecommerce:  11%|█         | 4/38 [00:07<00:54,  1.61s/it][transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`

ecommerce A_close_up_shot_of_a_fountain_pen_with_an_ink_bottle_highlighted_by_warm_bokeh_lights_in_the_background.jpg {'foreground': 'pen', 'background': 'blurred_lights', 'relation': 'object_with_background'} 1.43s

qwen3-vl-2b_4bit_local ecommerce:  13%|█▎        | 5/38 [00:08<00:51,  1.55s/it][transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`

ecommerce A_hand_holds_a_mushroom_themed_cup_indoors_focusing_on_coziness_with_a_blurred_screen_in_the_background.jpg {'foreground': 'coffee_mug', 'background': 'blurred_laptop', 'relation': 'object_with_background'} 1.45s

qwen3-vl-2b_4bit_local ecommerce:  16%|█▌        | 6/38 [00:09<00:47,  1.47s/it][transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`

ecommerce A_hiking_backpack_resting_on_rocky_terrain_with_Tatra_Mountains_in_the_background.jpg {'foreground': 'backpack', 'background': 'mountain', 'relation': 'object_with_background'} 1.31s

qwen3-vl-2b_4bit_local ecommerce:  18%|█▊        | 7/38 [00:11<00:42,  1.38s/it][transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`

ecommerce A_kettle_on_the_stove_with_a_teenage_boy_reading_a_book_in_the_background.jpg {'foreground': 'kettle', 'background': '', 'relation': 'object_with_background'} 1.20s

qwen3-vl-2b_4bit_local ecommerce:  21%|██        | 8/38 [00:12<00:39,  1.30s/it][transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`

ecommerce A_Mobile_phone_charging_on_a_marble_table_with_a_pen_wallet_and_note_book_in_the_background.jpg {'foreground': 'phone', 'background': '', 'relation': 'object_with_background'} 1.14s

qwen3-vl-2b_4bit_local ecommerce:  24%|██▎       | 9/38 [00:13<00:38,  1.33s/it][transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`

ecommerce A_person_holding_up_a_pair_of_sunglasses_with_the_ocean_in_the_background.jpg {'foreground': 'sunglasses', 'background': 'ocean', 'relation': 'object_with_background'} 1.39s

qwen3-vl-2b_4bit_local ecommerce:  26%|██▋       | 10/38 [00:15<00:38,  1.36s/it][transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`

ecommerce A_red_mug_on_a_coaster_with_a_blurred_person_in_the_background_indoors.jpg {'foreground': 'coffee_mug', 'background': 'blurred_lights', 'relation': 'object_with_background'} 1.43s

qwen3-vl-2b_4bit_local ecommerce:  29%|██▉       | 11/38 [00:16<00:37,  1.39s/it][transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`

ecommerce A_smartphone_capturing_a_scenic_view_of_a_pebble_beach_with_blurred_hills_in_the_background.jpg {'foreground': 'phone', 'background': 'ocean', 'relation': 'object_with_background'} 1.46s

qwen3-vl-2b_4bit_local ecommerce:  32%|███▏      | 12/38 [00:17<00:36,  1.41s/it][transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`

ecommerce A_striped_mug_in_focus_with_a_warm_artistic_bokeh_effect_in_the_background.jpg {'foreground': 'coffee_mug', 'background': 'blurred_lights', 'relation': 'object_with_background'} 1.45s

qwen3-vl-2b_4bit_local ecommerce:  34%|███▍      | 13/38 [00:19<00:35,  1.41s/it][transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`

ecommerce A_vintage_camera_on_a_table_with_a_blurred_woman_in_the_background_holding_her_head.jpg {'foreground': 'camera', 'background': 'woman', 'relation': 'object_with_background'} 1.41s

qwen3-vl-2b_4bit_local ecommerce:  37%|███▋      | 14/38 [00:20<00:34,  1.43s/it][transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`

ecommerce Artistic_shot_of_a_vintage_camera_with_blurred_digital_images_in_the_background.jpg {'foreground': 'camera', 'background': '', 'relation': 'object_with_background'} 1.47s

qwen3-vl-2b_4bit_local ecommerce:  39%|███▉      | 15/38 [00:22<00:31,  1.36s/it][transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`

ecommerce Bright_yellow_mug_placed_on_concrete_with_blurred_urban_architecture_in_the_background.jpg {'foreground': 'coffee_mug', 'background': 'urban_architecture', 'relation': 'object_with_background'} 1.19s

qwen3-vl-2b_4bit_local ecommerce:  42%|████▏     | 16/38 [00:23<00:29,  1.34s/it][transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`

ecommerce Camera_on_log_with_snowy_mountains_in_background.jpg {'foreground': 'camera', 'background': 'mountain', 'relation': 'object_with_background'} 1.30s

qwen3-vl-2b_4bit_local ecommerce:  45%|████▍     | 17/38 [00:24<00:28,  1.35s/it][transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`

ecommerce Camera_on_tripod_capturing_a_cityscape_at_night_with_blurred_lights_in_the_background.jpg {'foreground': 'camera', 'background': 'blurred_lights', 'relation': 'object_with_background'} 1.38s

qwen3-vl-2b_4bit_local ecommerce:  47%|████▋     | 18/38 [00:25<00:26,  1.33s/it][transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`

ecommerce Close_up_of_a_bar_of_green_soap_with_a_blank_white_label_resting_on_a_gray_surface_with_a_white_towel_in_the_background.jpg {'foreground': 'soap', 'background': 'towel', 'relation': 'object_with_background'} 1.28s

qwen3-vl-2b_4bit_local ecommerce:  50%|█████     | 19/38 [00:27<00:26,  1.37s/it][transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`

ecommerce Close_up_of_a_decorative_Santa_mug_with_a_Christmas_tree_bokeh_in_the_background.jpg {'foreground': 'coffee_mug', 'background': 'blurred_lights', 'relation': 'object_with_background'} 1.46s

qwen3-vl-2b_4bit_local ecommerce:  53%|█████▎    | 20/38 [00:28<00:24,  1.36s/it][transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`

ecommerce Close_up_of_a_DSLR_camera_on_a_desk_in_a_modern_office_setting_with_people_in_the_background.jpg {'foreground': 'camera', 'background': 'people', 'relation': 'object_with_background'} 1.34s

qwen3-vl-2b_4bit_local ecommerce:  55%|█████▌    | 21/38 [00:30<00:22,  1.33s/it][transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`

ecommerce Close_up_of_a_professional_DSLR_camera_with_people_blurred_in_the_background.jpg {'foreground': 'camera', 'background': 'people', 'relation': 'object_with_background'} 1.25s

qwen3-vl-2b_4bit_local ecommerce:  58%|█████▊    | 22/38 [00:31<00:21,  1.35s/it][transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`

ecommerce Close_up_of_a_vintage_camera_on_a_café_table_with_a_dessert_in_the_background.jpg {'foreground': 'camera', 'background': 'dessert', 'relation': ''} 1.40s

qwen3-vl-2b_4bit_local ecommerce:  61%|██████    | 23/38 [00:32<00:19,  1.32s/it][transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`

ecommerce Close_up_of_alarm_clock_with_man_sleeping_in_the_background_Cape_Town_South_Africa.jpg {'foreground': 'alarm_clock', 'background': 'man', 'relation': 'object_with_background'} 1.25s

qwen3-vl-2b_4bit_local ecommerce:  63%|██████▎   | 24/38 [00:33<00:18,  1.30s/it][transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`

ecommerce Close_up_of_water_bottle_in_locker_room_with_an_athlete_in_the_background.jpg {'foreground': 'water_bottle', 'background': 'man', 'relation': 'object_with_background'} 1.23s

qwen3-vl-2b_4bit_local ecommerce:  66%|██████▌   | 25/38 [00:35<00:17,  1.31s/it][transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`

ecommerce Elegant_black_perfume_bottle_placed_on_a_textured_surface_with_vibrant_flowers_in_the_background_during_daylight.jpg {'foreground': 'perfume_bottle', 'background': 'flowers', 'relation': 'object_with_background'} 1.34s

qwen3-vl-2b_4bit_local ecommerce:  68%|██████▊   | 26/38 [00:36<00:16,  1.35s/it][transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`

ecommerce Flower_vase_on_window_sill_with_father_and_son_in_background.jpg {'foreground': 'flower_vase', 'background': 'man', 'relation': 'object_with_background'} 1.44s

qwen3-vl-2b_4bit_local ecommerce:  71%|███████   | 27/38 [00:38<00:15,  1.37s/it][transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`

ecommerce Golden_sunglasses_rest_on_a_table_by_the_beach_with_a_serene_sunset_and_palm_trees_in_the_background.jpg {'foreground': 'sunglasses', 'background': 'ocean', 'relation': 'object_with_background'} 1.42s

qwen3-vl-2b_4bit_local ecommerce:  74%|███████▎  | 28/38 [00:39<00:13,  1.37s/it][transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`

ecommerce Hand_holding_a_coffee_cup_at_night_with_blurred_city_lights_in_the_background.jpg {'foreground': 'coffee_mug', 'background': 'blurred_lights', 'relation': 'object_with_background'} 1.37s

qwen3-vl-2b_4bit_local ecommerce:  76%|███████▋  | 29/38 [00:40<00:12,  1.36s/it][transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`

ecommerce Laptop_on_wooden_table_in_a_loft_flat_with_man_at_the_window_in_background.jpg {'foreground': 'laptop', 'background': 'man', 'relation': 'object_with_background'} 1.33s

qwen3-vl-2b_4bit_local ecommerce:  79%|███████▉  | 30/38 [00:42<00:10,  1.33s/it][transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`

ecommerce Notebook_and_coffee_cup_in_modern_informal_office_with_man_and_woman_in_background.jpg {'foreground': 'coffee_mug', 'background': 'people', 'relation': 'object_with_background'} 1.27s

qwen3-vl-2b_4bit_local ecommerce:  82%|████████▏ | 31/38 [00:43<00:09,  1.31s/it][transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`

ecommerce Open_book_with_bookshelf_in_the_background.jpg {'foreground': 'book', 'background': 'bookshelf', 'relation': 'object_with_background'} 1.27s

qwen3-vl-2b_4bit_local ecommerce:  84%|████████▍ | 32/38 [00:44<00:07,  1.33s/it][transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`

ecommerce Red_lentils_in_glass_jar_with_cooking_oil_bottle_and_woman_in_background_at_store.jpg {'foreground': 'jar', 'background': 'bookshelf', 'relation': 'object_with_background'} 1.38s

qwen3-vl-2b_4bit_local ecommerce:  87%|████████▋ | 33/38 [00:46<00:06,  1.37s/it][transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`

ecommerce Red_mug_with_bokeh_Christmas_lights_in_the_background_evoking_holiday_warmth_and_coziness.jpg {'foreground': 'coffee_mug', 'background': 'blurred_lights', 'relation': 'object_with_background'} 1.46s

qwen3-vl-2b_4bit_local ecommerce:  89%|████████▉ | 34/38 [00:47<00:05,  1.35s/it][transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`

ecommerce Shaker_bottle_with_woman_working_out_in_the_background.jpg {'foreground': 'water_bottle', 'background': 'blurred_lights', 'relation': 'object_with_background'} 1.29s

qwen3-vl-2b_4bit_local ecommerce:  92%|█████████▏| 35/38 [00:48<00:03,  1.32s/it][transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`

ecommerce Stylish_golden_glasses_with_colorful_bokeh_of_Dhaka_nightlife_in_the_background.jpg {'foreground': 'sunglasses', 'background': 'blurred_lights', 'relation': 'object_with_background'} 1.25s

qwen3-vl-2b_4bit_local ecommerce:  95%|█████████▍| 36/38 [00:49<00:02,  1.29s/it][transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`

ecommerce Stylish_handbag_with_a_horse_in_the_background.jpg {'foreground': 'handbag', 'background': 'horse', 'relation': 'object_with_background'} 1.23s

qwen3-vl-2b_4bit_local ecommerce:  97%|█████████▋| 37/38 [00:51<00:01,  1.27s/it][transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`

ecommerce Tortoiseshell_sunglasses_resting_on_a_sandy_beach_with_ocean_waves_in_the_background.jpg {'foreground': 'sunglasses', 'background': 'ocean', 'relation': 'object_with_background'} 1.21s

qwen3-vl-2b_4bit_local ecommerce: 100%|██████████| 38/38 [00:52<00:00,  1.38s/it]

ecommerce White_lamp_sits_in_foreground_adorned_with_silver_snowflake_ornament_and_unrecognizable_woman_in_yellow_in_background_adjusting_decorations_on_rwindow.jpg {'foreground': 'lamp', 'background': 'man', 'relation': 'object_with_background'} 1.08s

qwen3-vl-2b_4bit_local news:   0%|          | 0/15 [00:00<?, ?it/s][transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`
qwen3-vl-2b_4bit_local news:   7%|▋         | 1/15 [00:01<00:17,  1.23s/it][transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`

news Barack_Obama_at_Antalya.jpg {'foreground': 'Joe_Biden', 'background': 'Antalya', 'relation': 'people_at_event'} 1.23s

qwen3-vl-2b_4bit_local news:  13%|█▎        | 2/15 [00:02<00:16,  1.24s/it][transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`

news Barack_Obama_at_United_Nations.jpg {'foreground': 'Barack_Obama', 'background': 'United_Nations', 'relation': 'people_at_event'} 1.24s

qwen3-vl-2b_4bit_local news:  20%|██        | 3/15 [00:03<00:16,  1.33s/it][transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`

news Barack_Obama_at_White_House_Correspondents_Dinner.jpg {'foreground': 'Barack_Obama', 'background': 'White_House_Correspondents_Dinner', 'relation': ''} 1.44s

qwen3-vl-2b_4bit_local news:  27%|██▋       | 4/15 [00:05<00:15,  1.39s/it][transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`

news Ben_Affleck_at_Argo_press_junket.jpg {'foreground': 'Ben_Affleck', 'background': 'Argo_press_junket', 'relation': 'people_at_event'} 1.49s

qwen3-vl-2b_4bit_local news:  33%|███▎      | 5/15 [00:06<00:14,  1.42s/it][transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`

news Brad_Pitt_at_Venice_Film_Festival.jpg {'foreground': 'Brad_Pitt', 'background': 'Venice_Film_Festival', 'relation': 'people_at_event'} 1.47s

qwen3-vl-2b_4bit_local news:  40%|████      | 6/15 [00:08<00:12,  1.35s/it][transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`

news Donald_Trump_at_NRCC.jpg {'foreground': 'Donald_Trump', 'background': 'NRCC', 'relation': 'people_at_event'} 1.21s

qwen3-vl-2b_4bit_local news:  47%|████▋     | 7/15 [00:10<00:13,  1.74s/it][transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`

news Donald_Trump_at_Oval_Office2.jpg {'foreground': 'Donald_Trump', 'background': 'Florida', 'relation': 'people_at_event'} 2.54s

qwen3-vl-2b_4bit_local news:  53%|█████▎    | 8/15 [00:15<00:20,  2.86s/it][transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`

news Donald_Trump_at_Oval_Office3.jpg {'foreground': 'Donald_Trump', 'background': 'White_House', 'relation': ''} 5.26s

qwen3-vl-2b_4bit_local news:  60%|██████    | 9/15 [00:17<00:14,  2.38s/it][transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`

news Donald_Trump_at_Panama_City.jpg {'foreground': 'Donald_Trump', 'background': 'White_House', 'relation': 'people_at_event'} 1.33s

qwen3-vl-2b_4bit_local news:  67%|██████▋   | 10/15 [00:18<00:10,  2.02s/it][transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`

news Donald_Trump_at_White_House9.jpg {'foreground': 'Donald_Trump', 'background': 'White_House', 'relation': 'people_at_location'} 1.22s

qwen3-vl-2b_4bit_local news:  73%|███████▎  | 11/15 [00:19<00:06,  1.73s/it][transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`

news Joe_Biden_at_Buffalo.jpg {'foreground': 'Joe_Biden', 'background': 'White_House', 'relation': 'people_at_event'} 1.08s

qwen3-vl-2b_4bit_local news:  80%|████████  | 12/15 [00:20<00:04,  1.56s/it][transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`

news Joe_Biden_at_Oval_Office.jpg {'foreground': 'Joe_Biden', 'background': 'White_House', 'relation': 'people_at_location'} 1.17s

qwen3-vl-2b_4bit_local news:  87%|████████▋ | 13/15 [00:22<00:03,  1.54s/it][transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`

news Joe_Biden_at_State_of_the_Union.jpg {'foreground': 'Joe_Biden', 'background': 'White_House', 'relation': 'people_at_event'} 1.47s

qwen3-vl-2b_4bit_local news:  93%|█████████▎| 14/15 [00:23<00:01,  1.43s/it][transformers] Kwargs passed to `processor.__call__` have to be in `processor_kwargs` dict, not in `**kwargs`

news Joe_Biden_at_White_House_Correspondents_Dinner.jpg {'foreground': 'Joe_Biden', 'background': 'White_House', 'relation': 'people_at_location'} 1.17s

qwen3-vl-2b_4bit_local news: 100%|██████████| 15/15 [00:24<00:00,  1.65s/it]

news Mr_Bezos_at_Florida.jpg {'foreground': 'Jeff_Bezos', 'background': 'White_House', 'relation': 'people_at_event'} 1.38s
1.45s/image

,model_name,source,acc,micro_f1,macro_f1,latency (s),cost ($/1k images)
0,qwen3-vl-2b_4bit_local,open-source,0.811,0.83,0.768,1.451,0.0

,model_name,ecom_fg_acc,ecom_fg_micro_f1,ecom_fg_macro_f1,ecom_bg_acc,ecom_bg_micro_f1,ecom_bg_macro_f1,ecom_rel_acc,ecom_rel_micro_f1,ecom_rel_macro_f1,...,ecom_acc,ecom_micro_f1,ecom_macro_f1,news_acc,news_micro_f1,news_macro_f1,acc,micro_f1,macro_f1,latency (s)
0,qwen3-vl-2b_4bit_local,0.974,0.974,0.941,0.737,0.778,0.741,0.974,0.987,0.987,...,0.895,0.915,0.858,0.6,0.614,0.621,0.811,0.83,0.768,1.451

## Colab GPU: Qwen3-VL-4B

In [ ]:
run("qwen3-vl-4b_colab")
show("qwen3-vl-4b_colab")

:

:

:

NameError: name 'run' is not defined

## Colab GPU: Qwen3-VL-8B, 4-bit

In [ ]:
run("qwen3-vl-8b_4bit_colab")
show("qwen3-vl-8b_4bit_colab")

## OpenRouter: Qwen3.8-27B

In [ ]:
run("qwen3.8-27b_openrouter")
show("qwen3.8-27b_openrouter")

## OpenRouter: Qwen3-VL-30B-A3B

In [ ]:
run("qwen3-vl-30b-a3b_openrouter")
show("qwen3-vl-30b-a3b_openrouter")

## Google Cloud Vision

In [ ]:
run("cloud-vision_google")
show("cloud-vision_google")

## Gemini: 3.1 Flash-Lite

In [ ]:
run("gemini-3.1-flash-lite_google")
show("gemini-3.1-flash-lite_google")

## Results

In [ ]:
display(pd.read_csv("results/overall_metrics.csv"))
pd.read_csv("results/metrics.csv")